"""Part 1: Expand BASE_LEXICON and add _pickFromPool in index.ts"""
import re

path = 'src/banter/index.ts'
with open(path, 'r', encoding='utf-8') as f:
    src = f.read()

# ── 1. Add _queues field + _pickFromPool method to BanterSystem ──────────────
OLD_FIELD = '  private sideMinGapMs = 0;\n'
NEW_FIELD = (
    '  private sideMinGapMs = 0;\n'
    '  private _queues = new Map<string, string[]>();\n'
    '\n'
    '  private _pickFromPool(arr: readonly string[], key: string): string {\n'
    '    let q = this._queues.get(key);\n'
    '    if (!q || q.length === 0) {\n'
    '      q = [...arr];\n'
    '      shuffleInPlace(this.rng, q);\n'
    '      this._queues.set(key, q);\n'
    '    }\n'
    '    return q.pop() ?? \'\';\n'
    '  }\n'
)
assert OLD_FIELD in src, 'Could not find sideMinGapMs field'
src = src.replace(OLD_FIELD, NEW_FIELD, 1)

# ── 2. Replace pick() lambda to use _pickFromPool ────────────────────────────
OLD_PICK = (
    '    const pick = (lex: keyof Lexicon): string => {\n'
    '      const arr = mergedLex[lex];\n'
    '      return arr[Math.floor(rng() * arr.length)] ?? \'\';\n'
    '    };\n'
)
NEW_PICK = (
    '    const pick = (lex: keyof Lexicon): string =>\n'
    '      this._pickFromPool(mergedLex[lex], `${me.id}:${lex}`);\n'
)
assert OLD_PICK in src, 'Could not find old pick() lambda'
src = src.replace(OLD_PICK, NEW_PICK, 1)

# ── 3. Replace BASE_LEXICON ──────────────────────────────────────────────────
def ts_arr(items, indent='    '):
    inner = '\n'.join(f"{indent}'{i.replace(chr(39), chr(92)+chr(39))}'," for i in items)
    return f'[\n{inner}\n  ]'

greet = [
    "I was born ready.",
    "Finally—someone worth my time.",
    "Let the games begin.",
    "Systems hot, target locked.",
    "Hope you stretched first.",
    "Another victim steps up.",
    "Let's see how fast you break.",
    "All warmed up and hungry.",
    "I've been waiting for this.",
    "Ready to write history.",
    "You signed up for this—remember that.",
    "Engines at full. Let's go.",
    "Here we go again.",
    "Time to separate the strong from the rubble.",
    "Let's skip the small talk.",
    "Show me what you've got.",
    "Calibrated. Locked. Ready.",
    "Odds are against you. Just saying.",
    "Step up—I don't bite. Hard.",
    "Combat is what I was made for.",
    "Another round, another lesson.",
    "I've dismantled better than you.",
    "Fear me or face me—same result.",
    "Running diagnostics. All good. You?",
    "I fight for the sheer joy of it.",
    "Let's keep this civilized—or not.",
    "Challenger detected. Processing.",
    "Standing by. Ready to dominate.",
    "I've been sharpening this all week.",
    "You volunteered for this. Respect.",
    "Combat mode: engaged.",
    "Targeting solutions: acquired.",
    "A fresh opponent—how refreshing.",
    "Today is a good day for victory.",
    "Pleasure to meet you. Briefly.",
    "Begin.",
    "Weapons free.",
    "Clear your head—you'll need focus.",
    "Nice arena. Shame about the match.",
    "This ends quickly, one way or another.",
    "Round one. Let's dance.",
    "I study my opponents. I've studied you.",
    "The arena chose well today.",
    "Welcome to your greatest challenge.",
    "Online and operational. Game on.",
    "Alert status: elevated. As it should be.",
    "New challenger. Same outcome.",
    "I live for these moments.",
    "Sensor sweep complete. I know you already.",
    "Let's find out who's real and who's hype.",
    "Status: excellent. Yours: unknown.",
    "Charge complete. Ready to engage.",
    "Threat assessed. Low. Proceeding anyway.",
    "Should I warm up? Nah, I'm good.",
    "I don't take days off.",
    "Your reputation preceded you. Still not scared.",
    "Arena recognized. Let's go.",
    "One of us walks out better. Guess who.",
    "Fueled up and ready to destroy.",
    "Shall we begin the formalities—or skip straight to the hurt?",
    "Opponent in range. Commencing.",
    "Don't hold back. I want the real you.",
    "I don't pull punches. Fair warning.",
    "This moment. Right here. Mine.",
    "Threat level: manageable.",
    "I've been saving this energy for you.",
    "All circuits go. Weapons primed.",
    "You look ready. You're not.",
    "Today's forecast: total domination.",
    "Come on then—let's see your best.",
    "Hungry. Focused. Ready.",
    "Zero hesitation. Full commitment.",
    "This is my arena.",
    "All systems nominal. Beginning engagement.",
    "I've rehearsed this. Have you?",
    "Welcome to the last mistake you'll make today.",
    "Steady pulse. Clear mind. Let's go.",
    "Power levels optimal. Engaging.",
    "One match. No excuses.",
    "Let's find your ceiling.",
    "I respect the challenge. I'll still win.",
    "Fresh match, same hunger.",
    "Right then. No warm-up needed.",
    "Focused. Committed. Inevitable.",
    "I hope you brought your best.",
    "Time to find out if the hype is real.",
    "I've beaten worse. And better. Doesn't matter.",
    "Threat logged. Response ready.",
]

hype = [
    "Ohhh, that had to hurt!",
    "Straight to the face!",
    "Filthy play!",
    "Didn't see that coming, huh?",
    "That's how you do it!",
    "Brutal finish!",
    "Clean execution!",
    "What a move!",
    "Textbook!",
    "Unreal!",
    "That's the one!",
    "Nothing left to chance!",
    "Precision strike!",
    "Surgical!",
    "The crowd goes wild!",
    "Now that's a hit!",
    "Maximum impact!",
    "Read it like a book!",
    "Beautiful!",
    "Dominant!",
    "One for the highlight reel!",
    "Absolutely relentless!",
    "No mercy!",
    "Point made!",
    "Sent!",
    "Snap!",
    "Lovely hit!",
    "Clean as a whistle!",
    "The form on that!",
    "Masterwork!",
    "Zero wasted motion!",
    "Speed! Power! Timing!",
    "I felt that from here!",
    "Outstanding execution!",
    "Immaculate!",
    "That one echoed!",
    "Explosive!",
    "Smart play!",
    "Committed fully—paid off!",
    "No hesitation!",
    "Iron delivery!",
    "That's combat at its finest!",
    "Snap decision, perfect result!",
    "Optimal!",
    "Champion form!",
    "Locked on and delivered!",
    "Not even close!",
    "Pure aggression, pure payoff!",
    "High quality work!",
    "Well timed!",
    "Crisp!",
    "The gap is widening!",
    "Controlled destruction!",
    "That sequence was flawless!",
    "Capitalized immediately!",
    "Ruthless efficiency!",
    "Hit the mark!",
    "Exactly as planned!",
    "They never even adjusted!",
    "Unflinching!",
    "Picked the opening and took it!",
    "Right through the defenses!",
    "Overwhelming!",
    "No room for doubt!",
    "Devastating on contact!",
    "Stripped it apart!",
    "Like they weren't even there!",
    "Sharp!",
    "Power behind every move!",
    "Max damage!",
    "That's a statement!",
    "Emphatic!",
    "Precise and punishing!",
    "Crunching hit!",
    "Couldn't be stopped!",
    "That'll leave a mark!",
    "No argument from me!",
    "Loaded hit!",
    "They're going to feel that!",
    "Pure class!",
    "Commanding!",
    "What a display!",
    "Staggering blow!",
    "Right on cue!",
    "Calculated and devastating!",
    "Cold. Efficient. Effective.",
    "Punishing exchange—one winner!",
    "Zero regrets on that!",
    "That's arena-level play!",
    "Lock-in!",
    "Committed and delivered!",
]

tauntSoft = [
    "Too easy.",
    "Yawn—try harder.",
    "That tickled.",
    "Is that your plan? Really?",
    "I'm just warming up.",
    "Don't fall asleep out here.",
    "You're making this boring.",
    "C'mon, I expected more.",
    "Give me a challenge.",
    "You sure about that strategy?",
    "Take your time. I'll wait.",
    "Still loading?",
    "Is that it?",
    "I've fought furniture harder than you.",
    "My warmup is more intense than this.",
    "You're making me feel guilty.",
    "That was... something.",
    "Bless your heart.",
    "Nice try, A for effort.",
    "I've seen better from beginners.",
    "You fight like you're reading a manual.",
    "Slow down, tiger. Wait—no, please don't.",
    "I've had tougher sparring with myself.",
    "Rookie move.",
    "You had something there. Almost.",
    "That was practice, right?",
    "One day you might land one.",
    "Keep going. Somewhere in there is a good hit.",
    "Your plan is showing—so is its flaws.",
    "My grandmother hits harder. And she's offline.",
    "Did you practice that?",
    "I'm trying to find the threat. Give me a second.",
    "Is this a drill?",
    "You're going to need a bigger move.",
    "Giving you every chance here.",
    "You might want to rethink your whole approach.",
    "I've seen stronger napkins.",
    "Barely scratched the paint.",
    "You hesitated. Again.",
    "That's a lot of wind-up for nothing.",
    "I counted three mistakes in that one move.",
    "Adorable attempt.",
    "Polite aggression. I like it.",
    "Not exactly terrifying.",
    "Still waiting for the part where I get worried.",
    "I've been hit by better and worse. This is closer to better—barely.",
    "That's a technique? Fascinating.",
    "Hold on, let me take notes on what not to do.",
    "One-trick and the trick isn't working.",
    "You're broadcasting every move.",
    "Sloppy. But at least you're committed.",
    "You look nervous.",
    "That's the warmup, surely.",
    "Okay, okay. You're trying.",
    "No harm, no foul. No progress either.",
    "I'm not even using good hand.",
    "Telegraphed that one from a mile out.",
    "That strategy needs a patch.",
    "You're outmatched and you know it.",
    "I could do this all day.",
    "Take a breath. You're rushing.",
    "Little flustered, are we?",
    "So far so predictable.",
    "That's cute.",
    "I respect the hustle. Not the execution.",
    "You've got spirit. That's something.",
    "Working hard, not smart.",
    "Less panic, more precision.",
    "Overcorrecting.",
    "You're chasing your own tail.",
    "Running out of ideas, are we?",
    "Slow is smooth, and smooth is not what this is.",
    "Wrong answer. Try again.",
    "Reaching.",
    "One step behind the whole time.",
    "You're fighting shadows.",
    "I'm seeing the same move, third time now.",
    "Your patterns are showing.",
    "Not your day, huh?",
    "I almost felt that one.",
    "Commitment without direction.",
    "That'll look great in the replay—for me.",
    "Stretch your legs. This might take a while.",
    "You're making this easy.",
    "The idea was good. The execution, less so.",
    "Keep pushing. Something might stick eventually.",
]

tauntHard = [
    "I'll break you piece by piece.",
    "I'm inevitable—get used to it.",
    "You're already finished, you just don't know it yet.",
    "Bow down or get crushed.",
    "Say goodnight.",
    "I'll grind you into scrap.",
    "You're nothing but target practice.",
    "This ends when I decide it ends.",
    "I don't stop until there's nothing left.",
    "You can't outlast me.",
    "You were outclassed from the opening bell.",
    "I am your end.",
    "There is no recovery from me.",
    "Submit. Now.",
    "I'll rip through every defense you have.",
    "Resistance is costing you.",
    "Crumble.",
    "I will bury you.",
    "You have nowhere to go.",
    "Your ruin is already written.",
    "I hunt. You flee. That's the math.",
    "There's no version of this where you win.",
    "You're already on borrowed time.",
    "I'll shatter that confidence completely.",
    "You've already lost—you just haven't accepted it.",
    "I've ended stronger than you.",
    "Nothing you try will stop this.",
    "Your strategy is a broken tool.",
    "I see through everything you do.",
    "You're fuel for my momentum.",
    "I am the worst thing that ever happened to you.",
    "Collapse.",
    "You'll remember this for a long time.",
    "Every move you make feeds mine.",
    "You're outmatched in every dimension.",
    "I've dissected your style. You have no surprises left.",
    "I will not be denied.",
    "You're fighting my shadow and losing.",
    "Overwhelm incoming.",
    "Your end is close. I can see it.",
    "I've been holding back. Not anymore.",
    "You are dust.",
    "I don't negotiate. I demolish.",
    "Every breath you take here is borrowed.",
    "Shock. Awe. Submission.",
    "Nothing you do matters now.",
    "I'll undo every plan you have.",
    "Stop prolonging this.",
    "Your clock is running down.",
    "I'm beyond your ability to stop.",
    "Refuse to yield—it won't help.",
    "You're fighting a losing war.",
    "Your armor means nothing to me.",
    "I am relentless and you are not.",
    "This outcome was decided before you stepped in.",
    "All roads lead to your defeat.",
    "I will pick you apart.",
    "You cannot keep pace.",
    "Extinction is the only outcome here.",
    "There's no ceiling to how hard I'll hit you.",
    "You should have prepared better.",
    "I have no mercy for the weak.",
    "Fight harder. It won't matter, but it's more fun.",
    "You're not a challenge. You're a target.",
    "I will not slow down.",
    "I'll wreck every defense.",
    "You can't handle what's coming.",
    "Suffering is your current trajectory.",
    "I feast on fights like this.",
    "Your resolve is brittle.",
    "I'll crash through you.",
    "You're in my arena now.",
    "There is no escape from what I am.",
    "I've broken the unbreakable.",
    "You're overmatched and the gap is growing.",
    "Every second you last is my gift to you.",
    "I am your ceiling—and I'm crushing it.",
    "The end comes from me.",
    "Kneel or be forced to.",
    "You're going to break. It's only a matter of time.",
    "I strike without hesitation or regret.",
    "You're an obstacle. I remove obstacles.",
    "Your spirit will fold before your body.",
    "I make it look effortless because it is.",
    "You'll lose all sense of hope shortly.",
    "The damage I deal is only going to increase.",
    "This is a one-way road and you're heading down it.",
]

praise = [
    "Not bad—for you.",
    "Okay, respect.",
    "That almost impressed me.",
    "Nice shot. Won't happen again.",
    "Lucky—but credit where it's due.",
    "I'll give you that one.",
    "Enjoy it, it won't last.",
    "Well played. Genuinely.",
    "That one I didn't see coming.",
    "Good read.",
    "Smart move.",
    "Solid.",
    "Clean.",
    "Hm. Better than I expected.",
    "That was disciplined.",
    "You've got something there.",
    "Can't fault that one.",
    "Sharp instinct.",
    "Respect.",
    "Nice line.",
    "Actually impressive.",
    "Good timing.",
    "Quality hit.",
    "I underestimated that.",
    "Okay. Fair play.",
    "That sequence was clever.",
    "I acknowledge it.",
    "Well executed.",
    "Noted. You've got range.",
    "Alright, earned that one.",
    "Better than my last opponent.",
    "You're more capable than I gave you credit for.",
    "That's legitimate skill.",
    "You adapted. Points for that.",
    "Efficient.",
    "Sneaky but effective.",
    "Good recovery.",
    "Nice counterpunch.",
    "That had weight behind it.",
    "Impressive footwork.",
    "Good awareness.",
    "Crisp delivery.",
    "I'll file that one away.",
    "That was textbook.",
    "Well spotted.",
    "You read me there.",
    "I can't deny that.",
    "Decent.",
    "A solid attempt and a solid hit.",
    "You adjusted well.",
    "That was earned.",
    "Measured and precise.",
    "Hard to argue with that.",
    "Neatly done.",
    "That's the right answer.",
    "Optimized.",
    "Tactical.",
    "A good move, honestly.",
    "I respect the discipline behind that.",
    "You've trained well.",
    "You found the gap.",
    "Excellent choice of target.",
    "That was intelligent.",
    "You kept your composure. Impressive.",
    "Controlled power.",
    "Tight execution.",
    "High quality.",
    "I won't give you another opening like that.",
    "You capitalized perfectly.",
    "No wasted motion.",
    "That was refined.",
    "I was off and you punished it—fair.",
    "Good pressure.",
    "You're sharper than you look.",
    "I'll need to adjust because of that.",
    "Perfect timing on that exchange.",
    "Economical and brutal.",
    "You forced that opening. Smart.",
    "I needed that challenge.",
    "You belong here.",
    "That deserves acknowledgment.",
    "Calculated correctly.",
    "You had the edge there.",
    "Take the point. I'll take the next ten.",
    "That's the kind of move I train for.",
    "I see now why you're here.",
]

pain = [
    "Tch—got me!",
    "That one stung!",
    "Cheap shot!",
    "You'll pay for that!",
    "Systems—glitching!",
    "Bleeding but not beaten.",
    "That the best pain you can deal?",
    "Ouch!",
    "Lucky!",
    "Felt that one.",
    "Point to you.",
    "Won't happen twice.",
    "Ohhh that connected!",
    "Sharp hit.",
    "That rattled something.",
    "You caught me open.",
    "Clean strike—I'll admit it.",
    "Systems report: impact detected.",
    "Ugh—well placed.",
    "That'll bruise.",
    "Okay, you have power.",
    "Stings! Keep going—I dare you.",
    "Nice shot. Really.",
    "I'm not done, just dented.",
    "You found a gap. Won't happen again.",
    "That had weight.",
    "Flickered for a second there.",
    "Took more damage than I'd like.",
    "Hull integrity dropping.",
    "You're faster than I thought.",
    "That cut deep.",
    "Caught me mid-stride.",
    "Took the hit—still standing.",
    "You're going to regret that.",
    "Well landed!",
    "I underestimated your reach.",
    "That's going to cost me.",
    "Good hit. Bad timing for me.",
    "Felt that through the armor.",
    "Oww—right on the mark.",
    "You're stronger than you look.",
    "That knocked something loose.",
    "I walked into that.",
    "My fault, but I'll repay it.",
    "That's a real hit.",
    "Armor took the worst, but still.",
    "Solid contact.",
    "I'm adjusting.",
    "That's going to leave a mark.",
    "You landed that well.",
    "I felt every bit of that.",
    "Took that one full force.",
    "Good timing.",
    "That was calculated—and it worked.",
    "You punished my mistake.",
    "A little shaken. A lot still standing.",
    "You exploited the opening.",
    "Properly rattled!",
    "You hit exactly where it counts.",
    "Oh, that was nasty.",
    "Core rattled. Still operational.",
    "Hit registered.",
    "Damage logged.",
    "That's added to my damage report.",
    "Note to self: don't leave that open again.",
    "Excellent strike. Annoying, but excellent.",
    "Systems: damaged. Spirit: intact.",
    "That one came fast.",
    "Felt it crack.",
    "I didn't block enough.",
    "Smart strike.",
    "You got through.",
    "Impact confirmed.",
    "That rang my bell.",
    "Impressive force behind that.",
    "Dented but not destroyed.",
    "Okay, you're for real.",
    "Took full damage on that.",
    "That was a proper hit.",
    "I'm recalibrating my defense.",
    "Hit at the worst angle.",
    "Harder than expected!",
    "I felt that in my core.",
    "One step closer to making me angry.",
    "You've got teeth after all.",
    "That forced me back.",
    "Alright—you can hit. I know now.",
]

comeback = [
    "Thought I was done? Cute.",
    "Time to flip the script.",
    "I don't die easy.",
    "Momentum's mine now.",
    "This is where it turns.",
    "Your lead won't save you.",
    "Now you're in trouble.",
    "Here comes the comeback.",
    "You should have finished when you had the chance.",
    "I've been worse off than this.",
    "The match doesn't end until I say so.",
    "That lead of yours is evaporating.",
    "Big mistake leaving me alive.",
    "I was studying you. Now I act.",
    "Think I'm beaten? Think again.",
    "Every second I'm still here is bad news for you.",
    "I've turned deficits like this before.",
    "The gap is closing.",
    "My turn now.",
    "You just woke me up.",
    "You had it. Past tense.",
    "You held back one moment too long.",
    "Clawing back one hit at a time.",
    "The momentum has shifted—feel it?",
    "You should have pressed. You didn't.",
    "Every setback tightens my resolve.",
    "I don't fold under pressure.",
    "You blinked—that was your only chance.",
    "Watch closely: this is a comeback.",
    "I've recalibrated. This changes everything.",
    "I've seen my weaknesses. Now I fix them.",
    "The tide turns when I decide.",
    "You were winning. Note the past tense.",
    "I adjust faster than you expect.",
    "Come back mode: active.",
    "I'm better now than at the start.",
    "You let me breathe—I'm taking advantage.",
    "This is the part where you panic.",
    "Your confidence is your weakness.",
    "The longer this goes, the better for me.",
    "You thought it was over. Amateur.",
    "I just needed to recalibrate.",
    "Pressure doesn't break me. It focuses me.",
    "You overcommitted—now I capitalize.",
    "Deficit noted. Correction applied.",
    "I'm more dangerous down than healthy.",
    "Fear the wounded fighter.",
    "This deficit only fuels me.",
    "Resilience is my core feature.",
    "I'm built for this exact scenario.",
    "I learned from every hit you landed.",
    "Second wind: engaged.",
    "I thrive when my back is against the wall.",
    "I climb from deeper holes than this.",
    "You want to see what I'm really capable of? Good.",
    "Rallying now—brace yourself.",
    "Still here. Still dangerous.",
    "I've stored every lesson from this fight.",
    "You're not going to like what comes next.",
    "Watch how fast this flips.",
    "Adversity is where I train best.",
    "I'm not done. Not even close.",
    "Your lead is a liability now.",
    "I was losing—I'm learning.",
    "Resilience doesn't have an off switch.",
    "This is my element.",
    "I reverse course on a dime.",
    "Reset. Reload. Redouble.",
    "Every loss is information. I'm using it.",
    "This deficit made me dangerous.",
    "The better I understand your style, the worse your day gets.",
    "Recalculated. Recommitting.",
    "Big swing incoming.",
    "From behind is where legends come back.",
    "You handed me everything I needed.",
    "One good run and your lead is gone.",
    "I fight smarter when I'm hungry.",
    "We're not done. Far from it.",
    "That lead kept you comfortable. Good.",
    "I'll chase this down to zero.",
    "You should have taken me out.",
    "Now I'm angry. Now I'm focused.",
    "Watch the scoreboard change.",
    "I've been in worse positions—and won.",
    "Time to make this interesting.",
    "The turnaround starts now.",
    "Don't count me out yet.",
]

nearDeath = [
    "Hah—still standing!",
    "One breath left—make it count.",
    "Barely holding together.",
    "I'm not done yet!",
    "You'll have to finish the job!",
    "Dripping oil, still deadly.",
    "One more scar for the collection.",
    "Critical. Not fatal.",
    "Still operational. Barely.",
    "You haven't closed the deal.",
    "Systems red. Will: green.",
    "One hit from the edge—and still here.",
    "I refuse.",
    "Don't celebrate yet.",
    "You'd better make the next one count.",
    "So close—yet here I stand.",
    "Hanging on by a thread. Still hanging.",
    "A little more and you'd have had me.",
    "You're going to have to do better than that.",
    "I've been in the red before. I've won from there.",
    "Not today.",
    "My finish line is behind you.",
    "Everything hurts and I'm still coming.",
    "Push me harder. See what happens.",
    "On the edge and I'm fine with that.",
    "Critical alert: I am still a threat.",
    "This is where lesser fighters fold. I don't fold.",
    "Zero quit in this build.",
    "Barely standing. Fully committed.",
    "I'll drag myself across that line if I have to.",
    "At my worst, I'm still dangerous.",
    "Hull breach—but the engine still burns.",
    "Scraped to the bone and still fighting.",
    "My threat level doesn't decrease with my health.",
    "The danger is not behind me. It's in front of you.",
    "One foot from the grave and still coming forward.",
    "Systems failing in all the wrong places. Still going.",
    "I am defined by moments exactly like this.",
    "This is the part I was built for.",
    "Less armor, more fury.",
    "You almost had it.",
    "A wounded predator is a hungry one.",
    "The closer to zero, the more I have to lose.",
    "If I fall, I fall forward.",
    "Lean. Low. Still lethal.",
    "Catastrophic damage. Unchanged resolve.",
    "All reserves engaged. Everything I have.",
    "This desperation? It's focus.",
    "You broke the machine—the pilot's still here.",
    "I'll finish this on fumes if I have to.",
    "Core compromised. Mission unchanged.",
    "You don't get to see me quit.",
    "I've got one good hit left. It's for you.",
    "End of the road for one of us. Not me.",
    "They'll tell this story: he was down and still won.",
    "You keep landing shots. I keep getting up.",
    "One percent isn't zero.",
    "I found a second wind you didn't know I had.",
    "The clock is counting down—against you, not me.",
    "I run better when everything's on the line.",
    "Desperation sharpens the mind.",
    "I wouldn't bet against me right now.",
    "If this is the end, I'll make it count.",
    "Last stand. Best stand.",
    "No health bar can measure determination.",
    "Almost got me—almost doesn't win.",
    "I am still a variable you haven't solved.",
    "Critical condition. Critical attention.",
    "Battered. Furious. Present.",
    "Don't mistake damage for defeat.",
    "I will not be a forgettable loss.",
    "You've beaten me down—you haven't beaten me.",
    "This is exactly the kind of spot I live for.",
    "I've got enough left for the finish.",
    "You opened the door—you didn't shut it.",
    "The fight goes on until one of us is gone.",
    "My reserves are empty. My resolve is not.",
    "There's something that doesn't show on sensors: will.",
    "Sparks flying, engine screaming, still going.",
    "I fight better the more desperate it gets.",
    "Still here. Still choosing to fight.",
    "You want it done? Come finish it.",
    "Low armor, high intensity.",
    "Damage is just data. I'm still processing.",
    "You've done real damage. But you haven't done enough.",
    "At my worst, I become my best.",
]

victory = [
    "Told you—you never had a chance.",
    "Down you go.",
    "Easy money.",
    "All wrapped up.",
    "You should've stayed home.",
    "Pathetic.",
    "Another name crossed off.",
    "Dominant.",
    "Clean finish.",
    "Exactly as expected.",
    "That was decided early.",
    "Never in doubt.",
    "Mastery on display.",
    "Not even close.",
    "Outstanding.",
    "Efficient. Effective. Done.",
    "Too slow, too weak.",
    "You had no answer for me.",
    "I'll be honest—I've had harder sparring sessions.",
    "Textbook victory.",
    "Sealed.",
    "You're done.",
    "Great effort. Wrong arena.",
    "This result was always coming.",
    "The gap was wider than it looked.",
    "You couldn't match the pace.",
    "You had moments. I had the match.",
    "That's how it's done.",
    "My methods are sound.",
    "You gave it everything—it wasn't enough.",
    "Decisive.",
    "Victory tastes the same every time.",
    "Well fought. Poorly won.",
    "Champion's finish.",
    "The scoreboard doesn't lie.",
    "I proved my point.",
    "The better core won today.",
    "Flawless in the ways that matter.",
    "Another one for the record.",
    "There was only ever one outcome.",
    "I won the moment I read your first move.",
    "Efficient takedown.",
    "You made it interesting. I made it mine.",
    "Executed on every level.",
    "The win was inevitable.",
    "From start to finish—mine.",
    "Every move I made was right.",
    "Checkmate.",
    "No regrets, no adjustments needed.",
    "The arena agrees: superior combatant wins.",
    "You had ambition. I had precision.",
    "Strength. Speed. Strategy. All mine.",
    "An excellent defeat. For you.",
    "I was always in control.",
    "Superior in every metric.",
    "All systems: green. Outcome: expected.",
    "Your tactics were solid. So was my counter.",
    "The gap was real and growing.",
    "I outlasted, outmaneuvered, outclassed.",
    "Victory is its own argument.",
    "I was calibrated for this.",
    "I took what I earned.",
    "Satisfying.",
    "Clean victory, no reservations.",
    "You're a worthy opponent. And you lost.",
    "I had this from the opening move.",
    "Secured.",
    "Mission accomplished.",
    "I won't remember the struggle. I'll remember the win.",
    "Dispatched.",
    "Handled.",
    "Concluded.",
    "Nothing you did surprised me.",
    "I was always ahead of the curve.",
    "You pushed me—I appreciated it.",
    "Hard fought, harder won.",
    "You did everything right and I still won.",
    "Another perfect record.",
    "The math was against you from the start.",
    "Next.",
    "I earned this.",
    "Thorough.",
    "Target neutralized.",
    "Total domination.",
    "Good game. Better champion.",
    "This is what peak performance looks like.",
    "Take the loss gracefully—I took this gracefully.",
    "Result confirmed.",
]

def build_lexicon_ts(d):
    lines = ['const BASE_LEXICON: Lexicon = {']
    for key, items in d.items():
        if isinstance(items[0], str) and key.startswith('emoji'):
            inner = ', '.join(f"'{i.replace(chr(39), chr(92)+chr(39))}'" for i in items)
            lines.append(f'  {key}: [{inner}],')
        elif key.startswith('kaomoji'):
            inner = ', '.join(f"'{i.replace(chr(39), chr(92)+chr(39))}'" for i in items)
            lines.append(f'  {key}: [{inner}],')
        else:
            lines.append(f'  {key}: [')
            for item in items:
                escaped = item.replace("'", "\\'")
                lines.append(f"    '{escaped}',")
            lines.append('  ],')
            lines.append('')
    lines.append('};')
    return '\n'.join(lines)

lexicon_data = {
    'greet': greet,
    'hype': hype,
    'tauntSoft': tauntSoft,
    'tauntHard': tauntHard,
    'praise': praise,
    'pain': pain,
    'comeback': comeback,
    'nearDeath': nearDeath,
    'victory': victory,
    'emojisPositive': ["'😎'", "'🔥'", "'💣'", "'🚀'", "'👑'"],
    'emojisNegative': ["'🤕'", "'💀'", "'😵'", "'💢'", "'☠️'"],
    'kaomojiPositive': ["'(•\\u0300ᴗ•\\u0301)و ̑̑'", "'(ง'\\u0300-'\\u0301)ง'", "'(⌐■_■)'", "'(≖‿≖)'", "'(¬‿¬)'"],
    'kaomojiNegative': ["'(×_×)'", "'(>︵<)'", "'(ಠ_ಠ)'", "'(ノಠ益ಠ)ノ彡┻━┻'", "'(;\\uff64\\u30c4\\uff64)'"],
}

# Build replacement lexicon TS block preserving emoji arrays as raw
new_lex_lines = ['const BASE_LEXICON: Lexicon = {']
for key, items in lexicon_data.items():
    if key in ('emojisPositive', 'emojisNegative', 'kaomojiPositive', 'kaomojiNegative'):
        pass  # skip, we'll keep the original emoji lines
    else:
        new_lex_lines.append(f'  {key}: [')
        for item in items:
            escaped = item.replace("'", "\\'")
            new_lex_lines.append(f"    '{escaped}',")
        new_lex_lines.append('  ],')
        new_lex_lines.append('')
new_lex_lines.append(
    "  emojisPositive: ['\\U0001F60E', '\\U0001F525', '\\U0001F4A3', '\\U0001F680', '\\U0001F451'],\n"
    "  emojisNegative: ['\\U0001F915', '\\U0001F480', '\\U0001F635', '\\U0001F4A2', '\\U2620\\uFE0F'],\n"
    "\n"
    "  kaomojiPositive: ['(\u2022\u0300\u1D17\u2022\u0301)\u0648 \u0361\u0361', '(\u0e07\u2019\u0300-\u2019\u0301)\u0e07', '(\u2310\u25a0_\u25a0)', '(\u2256\u203f\u2256)', '(\u00ac\u203f\u00ac)'],\n"
    "  kaomojiNegative: ['(\u00d7_\u00d7)', '(>\ufe35<)', '(\u0ca0_\u0ca0)', '(\u30ce\u0ca0\u76ca\u0ca0)\u30ce\u5f61\u253b\u2501\u253b', '(;\uff64\u30c4\uff64)'],\n"
)
new_lex_lines.append('};')

# Actually, let's keep it simple and just keep the emoji/kaomoji lines from the original
# We'll replace just the text arrays, leaving the emoji/kaomoji lines intact

# Find the *uncommented* BASE_LEXICON block in src
# (The file also has a commented-out // const BASE_LEXICON above the real one)
search = '\nconst BASE_LEXICON: Lexicon = {'
lex_start = src.index(search) + 1  # +1 to skip the leading \n
lex_end = src.index('\n};', lex_start) + 3  # include the closing };\n

original_lex = src[lex_start:lex_end]

# Extract emoji/kaomoji lines from original
emoji_lines = []
for line in original_lex.split('\n'):
    if any(k in line for k in ['emojisPositive', 'emojisNegative', 'kaomojiPositive', 'kaomojiNegative']):
        emoji_lines.append(line)

# Build new lexicon
new_lex_parts = ['const BASE_LEXICON: Lexicon = {']
text_keys = ['greet', 'hype', 'tauntSoft', 'tauntHard', 'praise', 'pain', 'comeback', 'nearDeath', 'victory']
for key in text_keys:
    new_lex_parts.append(f'  {key}: [')
    for item in lexicon_data[key]:
        escaped = item.replace("'", "\\'")
        new_lex_parts.append(f"    '{escaped}',")
    new_lex_parts.append('  ],')
    new_lex_parts.append('')

for line in emoji_lines:
    new_lex_parts.append(line)
new_lex_parts.append('};')

new_lex_block = '\n'.join(new_lex_parts)

src = src[:lex_start] + new_lex_block + src[lex_end:]

with open(path, 'w', encoding='utf-8', newline='\n') as f:
    f.write(src)

print('index.ts updated successfully.')
print(f'BASE_LEXICON: {sum(len(lexicon_data[k]) for k in text_keys)} total lines across {len(text_keys)} categories')
