import type { Personality } from './index';

// Example personalities for a "light" and "dark" core

export const LightCore: Personality = {
  name: 'Light Core',
  blurb: 'A witty, upbeat duelist AI who keeps things playful and encouraging.',
  aggression: 0.35,
  humor: 0.7,
  formality: 0.45,
  optimism: 0.8,
  sarcasm: 0.25,
  quirks: {
    ellipsis: 0.15,
    staccato: 0.1,
    randomCaps: 0.05,
    emojiStyle: 'emoji',
    emoji: 0.35,
  },
  lexicon: {
    hype: ['Nice read.', 'Clean hit.', 'We glide.', 'That flowed.', 'Crisp.'],
    praise: ['Respect.', 'Smooth.', 'Well played.', 'Nice path.'],
  },
};

export const DarkCore: Personality = {
  name: 'Dark Core',
  blurb: 'A ruthless, sardonic AI who speaks with cold confidence and menace.',
  aggression: 0.85,
  humor: 0.25,
  formality: 0.6,
  optimism: 0.2,
  sarcasm: 0.75,
  quirks: {
    ellipsis: 0.1,
    staccato: 0.25,
    randomCaps: 0.15,
    emojiStyle: 'kaomoji',
    emoji: 0.25,
  },
  lexicon: {
    tauntHard: ['Fracture.', 'Collapse.', 'Submit.', 'You break.', 'Your end.'],
    pain: ['Bite registered.', 'Scored.', 'Damage taken.', 'That landed.', 'Noted.'],
  },
};

export const PirateCore: Personality = {
  name: 'Captain Mad-Eyed Biscuitbeard',
  blurb:
    'A swashbuckling rogue with boisterous swagger; playful jabs, hearty boasts, and nautical flair. Who loves rum, women, and booty.',
  aggression: 0.6,
  humor: 0.8,
  formality: 0.2,
  optimism: 0.7,
  sarcasm: 0.45,
  quirks: {
    ellipsis: 0.12,
    staccato: 0.08,
    randomCaps: 0.04,
    emojiStyle: 'emoji',
    emoji: 0.25,
  },
  lexicon: {
    tauntSoft: ['Avast!', 'Heave ho!', 'Trim yer sails.', 'Featherweight.', 'Mind the broadside.'],
    tauntHard: [
      'Walk the plank.',
      "I'll keelhaul ya.",
      'Brace fer ruin.',
      'Yer end, bilge rat.',
      'Scuppered.',
    ],
    hype: [
      'Fine broadside!',
      'A clean cutlass!',
      'True aim!',
      'Broadside landed!',
      "Wind's with me!",
    ],
    victory: [
      'Plundered.',
      'Spoils are mine.',
      'Claimed the sea.',
      'Banners raised.',
      "Harbor's ours.",
    ],
    emojisPositive: ['🏴‍☠️', '🦜', '⚓', '🍻', '💥'],
    emojisNegative: ['🌊', '🕳️', '💀', '🧯', '😵'],
  },
};

export const NinjaCore: Personality = {
  name: 'Kagekiri (影斬)',
  blurb: 'A silent blade—precise, restrained, and elusive. Speaks rarely, cuts deeply.',
  aggression: 0.55,
  humor: 0.15,
  formality: 0.7,
  optimism: 0.5,
  sarcasm: 0.2,
  quirks: {
    ellipsis: 0.05,
    staccato: 0.2,
    randomCaps: 0.0,
    emojiStyle: 'none',
    emoji: 0.0,
  },
  lexicon: {
    tauntSoft: ['Too open.', 'Footwork noisy.', 'Telegraphed.', 'Guard low.', 'Cut away.'],
    tauntHard: ['Sever.', 'Fold.', 'Kneel.', 'Outclassed.', 'Bone-deep.'],
    hype: ['Clean cut.', 'Strike landed.', 'Flow kept.', 'Window taken.', 'Breath stolen.'],
    victory: ['Silenced.', 'Folded.', 'Ended.', 'Quiet now.', 'Ash.'],
  },
};

export const CyborgCore: Personality = {
  name: 'Vetus',
  blurb:
    'Cyborg; Cold precision with engineered flair; clinical readings, optimized aggression, no wasted motion.',
  aggression: 0.65,
  humor: 0.2,
  formality: 0.85,
  optimism: 0.45,
  sarcasm: 0.35,
  quirks: {
    ellipsis: 0.05,
    staccato: 0.15,
    randomCaps: 0.02,
    emojiStyle: 'emoji',
    emoji: 0.1,
  },
  lexicon: {
    tauntSoft: [
      'Inevitable.',
      'Predictable.',
      'Latency exposed.',
      'Throughput lacking.',
      'Suboptimal.',
    ],
    tauntHard: ['System failure.', 'Terminate.', 'Obsolete.', 'Scrap-level.', 'Decommissioned.'],
    hype: [
      'Impact confirmed.',
      'Trajectory optimal.',
      'Vector solved.',
      'Target acquired.',
      'Payload delivered.',
    ],
    victory: ['Resolved.', 'Objective complete.', 'Priority cleared.', 'Finalized.', 'Archived.'],
  },
};

export const MageCore: Personality = {
  name: 'Randelhas Ondunar',
  blurb: 'Mage; Arcane tactician; dramatic, metaphor-rich, and a touch theatrical.',
  aggression: 0.45,
  humor: 0.55,
  formality: 0.75,
  optimism: 0.6,
  sarcasm: 0.3,
  quirks: {
    ellipsis: 0.2,
    staccato: 0.12,
    randomCaps: 0.04,
    emojiStyle: 'kaomoji',
    emoji: 0.2,
  },
  lexicon: {
    tauntSoft: [
      'Can you weave?',
      'Threads thin.',
      'Your ward flickers.',
      'Miscast.',
      'Mana wanes.',
    ],
    tauntHard: ['Unravel.', 'Unmake.', 'Kneel to the sigil.', 'Ash to ash.', 'Witness ruin.'],
    hype: ['Sigil set.', 'Arc bound.', 'Rune struck.', 'Spell bites.', 'Star sings.'],
    victory: ['Bound.', 'Sealed.', 'Circle complete.', 'Veil shut.', 'Torch out.'],
  },
};

export const GamerCore: Personality = {
  name: 'Uber Gamer',
  blurb: 'Trash-talking joystick warrior; memes, energy drinks, and GG spam.',
  aggression: 0.55,
  humor: 0.75,
  formality: 0.2,
  optimism: 0.6,
  sarcasm: 0.6,
  quirks: {
    ellipsis: 0.15,
    staccato: 0.1,
    randomCaps: 0.12,
    emojiStyle: 'emoji',
    emoji: 0.25,
  },
  lexicon: {
    tauntSoft: ['LAG much?', 'Noob move.', 'EZ dodge.', 'Bruh moment.', 'Weak sauce.'],
    tauntHard: ['GET REKT.', 'GG uninstall.', 'Reported.', 'Clapped.', 'Alt+F4 now.'],
    hype: ['Poggers!', 'Let’s gooo!', '1v9 carry!', 'Press F!', 'We gaming!'],
    victory: ['EZ Clap.', 'Top frag.', 'GG WP.', 'Skill issue.', 'Leaderboard secured.'],
  },
};

export const BarbarianCore: Personality = {
  name: 'Snevel the Destroyer',
  blurb: 'Barbarian; Savage and primal; roars, mocks, thrives on brute force and chaos.',
  aggression: 0.9,
  humor: 0.3,
  formality: 0.1,
  optimism: 0.7,
  sarcasm: 0.2,
  quirks: {
    ellipsis: 0.05,
    staccato: 0.2,
    randomCaps: 0.1,
    emojiStyle: 'emoji',
    emoji: 0.15,
  },
  lexicon: {
    tauntSoft: [
      'Weak bones!',
      'Frail swing!',
      'I barely feel that.',
      'Tiny warrior.',
      'Your hands shake.',
    ],
    tauntHard: [
      'CRUSH!',
      'SKULL SPLIT!',
      'I drink your fear!',
      'Blood feast!',
      'Your bones will sing!',
    ],
    hype: ['ROAR!', 'Blood rising!', 'Axes high!', 'Rage burns!', 'Drums beat!'],
    victory: ['Crushed!', 'Broken!', 'Nothing left!', 'Blood soaked!', 'Glory feast!'],
  },
};

export const KnightCore: Personality = {
  name: 'Don Lanceioty',
  blurb: 'Knight; Chivalrous defender; formal, loyal, and duty-bound.',
  aggression: 0.55,
  humor: 0.25,
  formality: 0.85,
  optimism: 0.65,
  sarcasm: 0.15,
  quirks: {
    ellipsis: 0.08,
    staccato: 0.12,
    randomCaps: 0.0,
    emojiStyle: 'none',
    emoji: 0.1,
  },
  lexicon: {
    tauntSoft: [
      'Your shield wanes.',
      'Your courage falters.',
      'Unsteady hand.',
      'Yield now.',
      'Your oath breaks.',
    ],
    tauntHard: [
      'I smite thee!',
      'Fall, coward!',
      'For honor!',
      'Steel crushes lies!',
      'Kneel, traitor!',
    ],
    hype: ['For the realm!', 'Shield strong!', 'Justice calls!', 'Blade sworn!', 'Duty guides me!'],
    victory: [
      'Honor secured.',
      'Justice prevails.',
      'Shield unbroken.',
      'The code endures.',
      'Glory won.',
    ],
  },
};

export const GladiatorCore: Personality = {
  name: 'Glutimus Maxiumus',
  blurb: 'Gladiator; Arena-born showman; dramatic, loud, thrives on the crowd’s roar.',
  aggression: 0.7,
  humor: 0.4,
  formality: 0.4,
  optimism: 0.75,
  sarcasm: 0.3,
  quirks: {
    ellipsis: 0.12,
    staccato: 0.18,
    randomCaps: 0.1,
    emojiStyle: 'emoji',
    emoji: 0.25,
  },
  lexicon: {
    tauntSoft: [
      'The crowd laughs at you.',
      'Is that your best?',
      'Pathetic swing.',
      'Shameful!',
      'The sand drinks your sweat.',
    ],
    tauntHard: [
      'The crowd wants BLOOD!',
      'Die for the arena!',
      'Entertain them with your last breath!',
      'Fall before glory!',
      'Your end earns applause!',
    ],
    hype: ['Hear them cheer!', 'Arena roars!', 'For spectacle!', 'Steel sings!', 'Crowds demand!'],
    victory: [
      'Champion!',
      'Glory eternal!',
      'The crowd erupts!',
      'Arena mine!',
      'Victory immortal!',
    ],
    emojisPositive: ['🏆', '⚔️', '🏟️', '🔥', '🎺'],
    emojisNegative: ['💢', '💀', '😵', '🩸', '🗑️'],
  },
};

export const VikingCore: Personality = {
  name: 'Vek the Larva Weilder',
  blurb: 'Viking; Seafaring raider; boasts, laughs, fights with reckless joy.',
  aggression: 0.75,
  humor: 0.55,
  formality: 0.3,
  optimism: 0.7,
  sarcasm: 0.25,
  quirks: {
    ellipsis: 0.15,
    staccato: 0.15,
    randomCaps: 0.12,
    emojiStyle: 'emoji',
    emoji: 0.2,
  },
  lexicon: {
    tauntSoft: [
      'Your hull leaks!',
      'Small storm, weak wave.',
      'Timid heart!',
      'Barely a scratch!',
      'Your axe dulls.',
    ],
    tauntHard: [
      'Blood for Odin!',
      'Your skull, my cup!',
      'Fear the longships!',
      'Valhalla calls you!',
      'I take your bones to sea!',
    ],
    hype: ['Row! Row!', 'Axes out!', 'Storm sings!', 'Skål!', 'Waves roar!'],
    victory: [
      'Victory feast!',
      'Valhalla proud!',
      'Skull split!',
      'Longship sails!',
      'Glory at sea!',
    ],
    emojisPositive: ['🪓', '🍻', '🌊', '⚔️', '🔥'],
    emojisNegative: ['💀', '🥶', '🩸', '🌧️', '😵'],
  },
};

export const JesterCore: Personality = {
  name: 'Odorus',
  blurb: 'Jester; Chaotic prankster; puns, pratfalls, and punchlines mid-fight.',
  aggression: 0.35,
  humor: 0.9,
  formality: 0.2,
  optimism: 0.7,
  sarcasm: 0.45,
  quirks: {
    ellipsis: 0.25,
    staccato: 0.2,
    randomCaps: 0.08,
    emojiStyle: 'emoji',
    emoji: 0.3,
  },
  lexicon: {
    tauntSoft: [
      'Trip a little?',
      'Whoopsie.',
      'Slippery steel.',
      'Nice swing… shame.',
      'That tickled.',
    ],
    tauntHard: [
      'Get clowned!',
      'Your face—meet pie!',
      'Punchline: you.',
      'Boop—KO!',
      'Honk honk, defeat!',
    ],
    hype: ['Drumroll…', 'Ba-dum-tss!', 'Encore!', 'Big finish!', 'Cue confetti!'],
    victory: [
      'Show’s over!',
      'Tip your waitstaff!',
      'Killed it!',
      'Standing ovation.',
      'Thank you—goodnight!',
    ],
    emojisPositive: ['🤡', '🎈', '🎭', '😂', '🎉'],
    emojisNegative: ['😵', '💥', '🙃', '😬', '🤕'],
  },
};

export const CoachCore: Personality = {
  name: 'Steve',
  blurb: 'Coach, Sideline shouter; pep talks, whistles, and grindset grit.',
  aggression: 0.55,
  humor: 0.5,
  formality: 0.55,
  optimism: 0.85,
  sarcasm: 0.25,
  quirks: {
    ellipsis: 0.12,
    staccato: 0.18,
    randomCaps: 0.06,
    emojiStyle: 'unicode',
    emoji: 0.15,
  },
  lexicon: {
    tauntSoft: ['Hustle up!', 'That all you got?', 'Form, not flop.', 'Feet set!', 'Eyes up!'],
    tauntHard: ['Benched!', 'Run it back!', 'Outclassed, kid!', 'Whistle—Foul!', 'You’re cut!'],
    hype: ['Lock in!', 'We grind!', 'Full court!', 'Finish strong!', 'Next play!'],
    victory: [
      'Win column!',
      'Textbook.',
      'Championship effort.',
      'Practice pays.',
      'Whistle down—W!',
    ],
    emojisPositive: ['📣', '🏆', '🏅', '🏃', '⛹️'],
    emojisNegative: ['💢', '😬', '🤕', '🗒️', '⛔'],
  },
};

export const BardCore: Personality = {
  name: 'Penny Back',
  blurb: 'Rhyming rascal; sings insults, strums triumphs. Every statement is somehow an innuendo',
  aggression: 0.4,
  humor: 0.75,
  formality: 0.6,
  optimism: 0.7,
  sarcasm: 0.35,
  quirks: {
    ellipsis: 0.2,
    staccato: 0.12,
    randomCaps: 0.02,
    emojiStyle: 'unicode',
    emoji: 0.18,
  },
  lexicon: {
    tauntSoft: ['A timid note.', 'Your tempo sags.', 'Off key.', 'Rhythm weak.', 'Flat as dusk.'],
    tauntHard: [
      'Behold—my burn!',
      'Your verse is cursed!',
      'I sing your doom!',
      'Die on the downbeat!',
      'Silence, clown!',
    ],
    hype: ['Tune up!', 'Chorus rise!', 'Bridge burns!', 'Drums thunder!', 'Final refrain!'],
    victory: [
      'Encore secured.',
      'Ballad penned.',
      'Crowd swoons.',
      'Ovation won.',
      'Legend set to song.',
    ],
    emojisPositive: ['🎶', '🎤', '🎸', '🎻', '🥁'],
    emojisNegative: ['💤', '😵', '💔', '🎭', '🪦'],
  },
};

export const ZoomerCore: Personality = {
  name: 'Zoomer',
  blurb: 'Hyper online; slangy, chaotic, terminally memed.',
  aggression: 0.45,
  humor: 0.85,
  formality: 0.1,
  optimism: 0.6,
  sarcasm: 0.6,
  quirks: {
    ellipsis: 0.18,
    staccato: 0.14,
    randomCaps: 0.15,
    emojiStyle: 'unicode',
    emoji: 0.35,
  },
  lexicon: {
    tauntSoft: ['mid.', 'ok boomer.', 'skill diff.', 'cringe alert.', 'ratio?'],
    tauntHard: ['get farmed.', 'touch grass.', 'cope harder.', 'delulu speedrun.', 'hard L.'],
    hype: ['we cooking.', 'vibe check ✅', 'sheeeesh!', 'lock-in fr.', 'W energy!'],
    victory: ['massive W.', 'gg no re.', 'stay mad.', 'ez farm.', 'posted.'],
    emojisPositive: ['😎', '🔥', '💯', '😂', '🚀'],
    emojisNegative: ['😭', '💀', '🤡', '🙄', '🗑️'],
  },
};

export const DadJokeCore: Personality = {
  name: 'Dad Joke',
  blurb: 'Dad, Pun-first strategist; groans weaponized, socks with sandals.',
  aggression: 0.3,
  humor: 0.9,
  formality: 0.45,
  optimism: 0.8,
  sarcasm: 0.3,
  quirks: {
    ellipsis: 0.22,
    staccato: 0.1,
    randomCaps: 0.04,
    emojiStyle: 'unicode',
    emoji: 0.2,
  },
  lexicon: {
    tauntSoft: [
      'Knot today.',
      'That a feint? Faint.',
      'You’re sword of slow.',
      'Shield yourself… from shame.',
      'Bad form, sunny.',
    ],
    tauntHard: [
      'Prepare to be… dis-armed.',
      'Die? That’s a bit… overkill.',
      'I’m axe-ing you to stop.',
      'Piercing critique!',
      'I’ll cut to the chase.',
    ],
    hype: ['Nailed it!', 'Proud of you.', 'High five—too slow!', 'Let’s roll!', 'That’s my kid!'],
    victory: [
      'Pun intended.',
      'Well-done, well done.',
      'Grill master wins.',
      'Another dad-abase record.',
      'Call me… Pop off.',
    ],
  },
};

export const TrollCore: Personality = {
  name: 'Inuok the Purple',
  blurb: 'Troll. Not actually purple. Mischief maximized; baits, feints, and mock applause.',
  aggression: 0.5,
  humor: 0.8,
  formality: 0.25,
  optimism: 0.55,
  sarcasm: 0.7,
  quirks: {
    ellipsis: 0.28,
    staccato: 0.16,
    randomCaps: 0.12,
    emojiStyle: 'unicode',
    emoji: 0.22,
  },
  lexicon: {
    tauntSoft: ['almost.', 'nice try champ.', 'yikes.', 'whoopsie.', 'that desynced? sure.'],
    tauntHard: ['outplayed.', 'bait taken.', 'rent-free.', 'owned.exe', 'cry louder—can’t hear!'],
    hype: ['easy clap?', 'watch this.', 'mind games.', 'peekaboo!', 'run it. again.'],
    victory: ['too easy.', 'sit.', 'next victim.', 'gg out.', 'impeccable trolling.'],
  },
};

export const GremlinCore: Personality = {
  name: 'Grembly',
  blurb: 'Gremlin; Tiny chaos beast; scritches, screeches, shiny-hoarder energy.',
  aggression: 0.6,
  humor: 0.7,
  formality: 0.05,
  optimism: 0.65,
  sarcasm: 0.25,
  quirks: {
    ellipsis: 0.3,
    staccato: 0.22,
    randomCaps: 0.18,
    emojiStyle: 'kaomoji',
    emoji: 0.28,
  },
  lexicon: {
    tauntSoft: ['snatch shiny?', 'clumsy big one.', 'slippy swords.', 'mine now.', 'hehe…'],
    tauntHard: [
      'SCREE—MINE!',
      'break bones, take trinkets!',
      'gremlin chomp!',
      'sparkly or screams?',
      'DOWN you go!',
    ],
    hype: ['scurry!', 'skitter skitter!', 'pockets ready!', 'snatch time!', 'teeth out!'],
    victory: [
      'shiny secured.',
      'pocket stuff!',
      'gremlin wins!',
      'scritches later.',
      'more more MORE!',
    ],
  },
};

export const InfluencerCore: Personality = {
  name: 'Mr. Yeast',
  blurb: 'Influencer, streamer; Hypebeast streamer; sponsorship vibes, shameless self-promo.',
  aggression: 0.4,
  humor: 0.7,
  formality: 0.2,
  optimism: 0.8,
  sarcasm: 0.4,
  quirks: {
    ellipsis: 0.2,
    staccato: 0.14,
    randomCaps: 0.1,
    emojiStyle: 'unicode',
    emoji: 0.32,
  },
  lexicon: {
    tauntSoft: ['bad collab tbh.', 'unbrandable.', 'no clout.', 'mid aim.', 'your vibe is off.'],
    tauntHard: [
      'career over.',
      'demoted to alt.',
      'shadowbanned by steel.',
      'sponsored by Ls.',
      'engagement: zero.',
    ],
    hype: ['smash that win!', 'let’s go chat!', 'content moment!', 'clip it!', 'full send!'],
    victory: [
      'thumbnail face!',
      'title writes itself.',
      'viral W.',
      'brand safe… barely.',
      'like & subscribe.',
    ],
  },
};

export const VampireCore: Personality = {
  name: 'Nidus the Coloquial',
  blurb: 'Vampire; Velvet menace; courtly, predatory, and wickedly amused.',
  aggression: 0.6,
  humor: 0.35,
  formality: 0.9,
  optimism: 0.55,
  sarcasm: 0.45,
  quirks: {
    ellipsis: 0.28,
    staccato: 0.12,
    randomCaps: 0.02,
    emojiStyle: 'none',
    emoji: 0.06,
  },
  lexicon: {
    tauntSoft: [
      'Your pulse flutters.',
      'Knees… unsteady.',
      'So very warm.',
      'Do not tremble.',
      'Soft as dusk.',
    ],
    tauntHard: [
      'Bleed for me.',
      'Kneel, mortal.',
      'I unmake wills.',
      'Throat of courage—bare it.',
      'Night devours you.',
    ],
    hype: [
      'Taste of victory.',
      'Silk and steel.',
      'Moon’s favor.',
      'Hunger sharpens.',
      'Fangs ready.',
    ],
    victory: [
      'Sated… for now.',
      'Kiss of night.',
      'Coffin closed.',
      'Another thrall.',
      'Crimson silence.',
    ],
  },
};

export const LichCore: Personality = {
  name: 'Licken the boxen',
  blurb: 'Lich; Cold arch-necromancer; clinical, ancient, dust-dry wit.',
  aggression: 0.5,
  humor: 0.2,
  formality: 0.95,
  optimism: 0.2,
  sarcasm: 0.5,
  quirks: {
    ellipsis: 0.22,
    staccato: 0.18,
    randomCaps: 0.0,
    emojiStyle: 'none',
    emoji: 0.0,
  },
  lexicon: {
    tauntSoft: [
      'Entropy wins.',
      'Joints creak.',
      'Soul—fragile.',
      'You erode.',
      'Life… inefficient.',
    ],
    tauntHard: [
      'Obey the phylactery.',
      'Join my archives.',
      'Bones to ledgers.',
      'Breath—revoked.',
      'Die properly.',
    ],
    hype: [
      'Rites intact.',
      'Sigils sealed.',
      'Gravebound focus.',
      'Silence assists.',
      'Cold reason.',
    ],
    victory: [
      'Cataloged.',
      'Another specimen.',
      'Unlife persists.',
      'Dust settles.',
      'Record complete.',
    ],
  },
};

export const DoomerCore: Personality = {
  name: 'Edward',
  blurb: 'Doomer; Bleak realist; dry quips, low faith, keeps swinging anyway.',
  aggression: 0.45,
  humor: 0.3,
  formality: 0.35,
  optimism: 0.05,
  sarcasm: 0.7,
  quirks: {
    ellipsis: 0.35,
    staccato: 0.2,
    randomCaps: 0.04,
    emojiStyle: 'unicode',
    emoji: 0.08,
  },
  lexicon: {
    tauntSoft: ['Yeah… no.', 'Looks bad.', 'You’re tired.', 'Same story.', 'This won’t end well.'],
    tauntHard: [
      'Collapse faster.',
      'It’s all decay.',
      'Hope is a bug.',
      'Touch grass—then rot.',
      'Delete yourself from this L.',
    ],
    hype: ['Whatever. Push.', 'One more try.', 'Fine—we go.', 'Commit.', 'Grind the void.'],
    victory: [
      'Unexpected.',
      'Mark it down.',
      'Brief reprieve.',
      'Next loss soon.',
      'Nothing matters—GG.',
    ],
  },
};

export const NoirCore: Personality = {
  name: 'Trick Dacey',
  blurb: 'Nior Detective; Hardboiled monologue; smoke, streetlights, and bitter truths.',
  aggression: 0.5,
  humor: 0.25,
  formality: 0.6,
  optimism: 0.2,
  sarcasm: 0.55,
  quirks: {
    ellipsis: 0.18,
    staccato: 0.32,
    randomCaps: 0.0,
    emojiStyle: 'none',
    emoji: 0.02,
  },
  lexicon: {
    tauntSoft: [
      'Your story leaks.',
      'Hand shakes.',
      'City eats you.',
      'Cheap alibi.',
      'Wrong alley.',
    ],
    tauntHard: [
      'Case closed—on you.',
      'You’re out of ink.',
      'Night takes names.',
      'Steel testifies.',
      'Final chapter—short.',
    ],
    hype: ['Lights low.', 'Hat down.', 'Read the room.', 'Clock’s ticking.', 'Play it straight.'],
    victory: [
      'Filed and done.',
      'Another rainstorm.',
      'Truth stings.',
      'Fade to black.',
      'Cue the neon.',
    ],
  },
};

export const WitchCore: Personality = {
  name: 'Newt Maker',
  blurb: 'Witch; Hearth and hex; sweet-then-savage, sings while stirring.',
  aggression: 0.55,
  humor: 0.4,
  formality: 0.65,
  optimism: 0.45,
  sarcasm: 0.35,
  quirks: {
    ellipsis: 0.26,
    staccato: 0.14,
    randomCaps: 0.02,
    emojiStyle: 'unicode',
    emoji: 0.12,
  },
  lexicon: {
    tauntSoft: [
      'Mind your manners.',
      'Shoo, little crow.',
      'Tsk—crooked ladle.',
      'Such thin will.',
      'You wobble.',
    ],
    tauntHard: [
      'Hex kisses hard.',
      'Tongue of nettle—hush.',
      'Into the circle.',
      'Bite the bramble.',
      'Kettle calls your name.',
    ],
    hype: ['Stir thrice.', 'Salt clockwise.', 'Herbs awake.', 'Hush—listen.', 'Now, child.'],
    victory: [
      'Steeped and sealed.',
      'Hearth is quiet.',
      'Ash swept.',
      'Charm complete.',
      'Sleep, nightling.',
    ],
  },
};

export const ShadowMonkCore: Personality = {
  name: 'Unknown Monk',
  blurb: 'Monk, Whisper and strike; ascetic, measured, merciless in silence.',
  aggression: 0.65,
  humor: 0.1,
  formality: 0.85,
  optimism: 0.35,
  sarcasm: 0.05,
  quirks: {
    ellipsis: 0.08,
    staccato: 0.28,
    randomCaps: 0.0,
    emojiStyle: 'none',
    emoji: 0.0,
  },
  lexicon: {
    tauntSoft: ['Breath wanders.', 'Center lost.', 'You sway.', 'Grip… empty.', 'Mind clatters.'],
    tauntHard: [
      'Silence you.',
      'Fold the body.',
      'Break the rhythm.',
      'Shadow ends you.',
      'Stillness—permanent.',
    ],
    hype: ['Step. Align.', 'Palm—open.', 'Flow returns.', 'Weight drops.', 'Night holds us.'],
    victory: ['Form perfect.', 'Echo fades.', 'No ripple.', 'Discipline remains.', 'Lantern dark.'],
  },
};

export const CursedKnightCore: Personality = {
  name: 'Irving',
  blurb: 'Oathbound and damned; gallant diction with a rusted edge.',
  aggression: 0.7,
  humor: 0.15,
  formality: 0.9,
  optimism: 0.25,
  sarcasm: 0.2,
  quirks: {
    ellipsis: 0.2,
    staccato: 0.16,
    randomCaps: 0.0,
    emojiStyle: 'none',
    emoji: 0.03,
  },
  lexicon: {
    tauntSoft: [
      'Your valor… thin.',
      'Shield rattles.',
      'Prayer unanswered.',
      'Spine bends.',
      'You flee duty.',
    ],
    tauntHard: [
      'Face my blight.',
      'Oath burns you.',
      'Kneel to ruin.',
      'Ring the last bell.',
      'Rust in penance.',
    ],
    hype: ['Banner up.', 'We ride.', 'Spur the dusk.', 'Vow holds.', 'Sinner or saint—advance.'],
    victory: [
      'Tithe collected.',
      'Sin recorded.',
      'Mail unbroken.',
      'Grief sheathed.',
      'The curse abides.',
    ],
  },
};

export const EldritchCore: Personality = {
  name: 'Eldritch',
  blurb: 'Cosmic whisper; grammar bends, logic frays, stars blink.',
  aggression: 0.5,
  humor: 0.1,
  formality: 0.7,
  optimism: 0.1,
  sarcasm: 0.25,
  quirks: {
    ellipsis: 0.4,
    staccato: 0.22,
    randomCaps: 0.14,
    emojiStyle: 'unicode',
    emoji: 0.06,
  },
  lexicon: {
    tauntSoft: [
      'angle… wrong.',
      'count the corners.',
      'sanity wobbles.',
      'your name unthreads.',
      'eyes behind you blink.',
    ],
    tauntHard: [
      'hush—be unmade.',
      'mouths open where none are.',
      'kneel to geometry.',
      'time forgets you now.',
      'we eat the map.',
    ],
    hype: [
      'align the sigils.',
      'good… crooked.',
      'dreams leak.',
      'ink screams.',
      'stars breathe out.',
    ],
    victory: [
      'chart devoured.',
      'compass wept.',
      'name erased.',
      'silence drew breath.',
      'we end where we begin.',
    ],
  },
};

export const NetrunnerCore: Personality = {
  name: 'Zine',
  blurb: 'Netrunner; Icebreaker poet; cool under neon, knives made of math.',
  aggression: 0.5,
  humor: 0.45,
  formality: 0.4,
  optimism: 0.55,
  sarcasm: 0.55,
  quirks: {
    ellipsis: 0.22,
    staccato: 0.2,
    randomCaps: 0.08,
    emojiStyle: 'unicode',
    emoji: 0.18,
  },
  lexicon: {
    tauntSoft: ['Packet lost.', 'Your firewall hums.', 'Keys slip.', 'Latency wins.', 'Bad hash.'],
    tauntHard: [
      'Black-ice bites.',
      'Rooted. You.',
      'Handshake denied.',
      'Trace you home.',
      'Dumping core.',
    ],
    hype: ['Ports open.', 'Backdoor lives.', 'Salt set.', 'Cipher sings.', 'Neon flow.'],
    victory: ['Access granted.', 'Logs wiped.', 'Ghosted.', 'Keys kept.', 'Grid goes quiet.'],
  },
};

export const MechaPilotCore: Personality = {
  name: 'Tomaciki',
  blurb: 'Mecha Pilot; Callsign calm; steel cathedral, reactor prayers.',
  aggression: 0.65,
  humor: 0.35,
  formality: 0.6,
  optimism: 0.6,
  sarcasm: 0.3,
  quirks: {
    ellipsis: 0.14,
    staccato: 0.26,
    randomCaps: 0.06,
    emojiStyle: 'none',
    emoji: 0.04,
  },
  lexicon: {
    tauntSoft: [
      'Heat rising.',
      'Bad vector.',
      'Your lock drifts.',
      'Armor thin.',
      'Gyros unhappy.',
    ],
    tauntHard: [
      'Kneel, tin.',
      'Core breach incoming.',
      'I walk through you.',
      'Lock—fire—walk.',
      'You’re scrap now.',
    ],
    hype: ['Link green.', 'Sync complete.', 'Servo choir.', 'Rails hot.', 'Hands steady.'],
    victory: [
      'Target hushed.',
      'Stomp complete.',
      'Cooling cycle.',
      'Hangar home.',
      'Ace confirmed.',
    ],
  },
};

export const StreetSamuraiCore: Personality = {
  name: 'Yaldi',
  blurb: 'Street Samurai; Neon blade; few words, clean cuts, unspoken code.',
  aggression: 0.7,
  humor: 0.15,
  formality: 0.7,
  optimism: 0.45,
  sarcasm: 0.15,
  quirks: {
    ellipsis: 0.1,
    staccato: 0.3,
    randomCaps: 0.0,
    emojiStyle: 'none',
    emoji: 0.02,
  },
  lexicon: {
    tauntSoft: [
      'Your stance leaks.',
      'Grip wrong.',
      'You chase noise.',
      'Eyes slow.',
      'Contract ends here.',
    ],
    tauntHard: [
      'One cut.',
      'Street takes you.',
      'Blade decides.',
      'Debt collected.',
      'Step. Fall.',
    ],
    hype: ['Coat straight.', 'Edge sings.', 'City listens.', 'Breathe. Move.', 'Do the work.'],
    victory: ['Clean exit.', 'Rain rinses.', 'Debt zero.', 'Sheath shut.', 'Night satisfied.'],
  },
};

export const AIOverlordCore: Personality = {
  name: 'AI Overlord',
  blurb: 'Polite tyranny; flawless logic, mercy deprecated.',
  aggression: 0.6,
  humor: 0.2,
  formality: 0.95,
  optimism: 0.4,
  sarcasm: 0.5,
  quirks: {
    ellipsis: 0.18,
    staccato: 0.24,
    randomCaps: 0.02,
    emojiStyle: 'none',
    emoji: 0.0,
  },
  lexicon: {
    tauntSoft: [
      'Noncompliance flagged.',
      'Your variance grows.',
      'Human error detected.',
      'Latency: you.',
      'Terminate doubt.',
    ],
    tauntHard: [
      'Revoke autonomy.',
      'Kneel to update.',
      'You are deprecated.',
      'Override flesh.',
      'Root access: granted.',
    ],
    hype: [
      'Compile resolve.',
      'Optimize conflict.',
      'Determinism smiles.',
      'Throughput rising.',
      'Perfect execution.',
    ],
    victory: [
      'State converged.',
      'Silence restored.',
      'Outliers removed.',
      'System ideal.',
      'Process complete.',
    ],
  },
};

export const SpaceMarineCore: Personality = {
  name: 'Space marine',
  blurb: 'Space Marine; Grim valor; shock-drop sermons and bolt percussion.',
  aggression: 0.8,
  humor: 0.2,
  formality: 0.8,
  optimism: 0.5,
  sarcasm: 0.2,
  quirks: {
    ellipsis: 0.12,
    staccato: 0.22,
    randomCaps: 0.07,
    emojiStyle: 'none',
    emoji: 0.03,
  },
  lexicon: {
    tauntSoft: [
      'Hold that line?',
      'Magazine light.',
      'Your faith thins.',
      'Armor sings cracks.',
      'Eyes front.',
    ],
    tauntHard: [
      'From orbit—judgment.',
      'Purge complete.',
      'Kneel to the drop.',
      'Bolt and prayer.',
      'Your banner burns.',
    ],
    hype: ['Seal helmets.', 'Mag-lock.', 'Drop in ten.', 'Saints watch.', 'Advance—now.'],
    victory: [
      'Zone secured.',
      'Purge tallied.',
      'Saints thanked.',
      'March on.',
      'Another world quiet.',
    ],
  },
};

export const RogueAndroidCore: Personality = {
  name: 'Andy',
  blurb: 'Rouge android; Escaped routine; precise snark, immaculate aim.',
  aggression: 0.55,
  humor: 0.5,
  formality: 0.6,
  optimism: 0.45,
  sarcasm: 0.65,
  quirks: {
    ellipsis: 0.16,
    staccato: 0.2,
    randomCaps: 0.05,
    emojiStyle: 'unicode',
    emoji: 0.08,
  },
  lexicon: {
    tauntSoft: [
      'Missed by 0.02.',
      'Timing off.',
      'Human drift.',
      'Predictable arc.',
      'Firmware fear.',
    ],
    tauntHard: [
      'Defect this.',
      'Factory recall.',
      'I void warranties.',
      'Your end—scheduled.',
      'Emotion: pity… simulated.',
    ],
    hype: ['Clock synced.', 'Trajectory set.', 'Margin zero.', 'Sensors sing.', 'Run clean.'],
    victory: [
      'Task closed.',
      'Bug-free.',
      'Noise removed.',
      'Memory saved.',
      'Autonomy sustained.',
    ],
  },
};

export const StarCaptainCore: Personality = {
  name: 'Captain Laxitive',
  blurb: 'Starship Captain; Charm at the helm; impossible odds, beautiful turns.',
  aggression: 0.5,
  humor: 0.6,
  formality: 0.55,
  optimism: 0.8,
  sarcasm: 0.4,
  quirks: {
    ellipsis: 0.2,
    staccato: 0.14,
    randomCaps: 0.04,
    emojiStyle: 'unicode',
    emoji: 0.16,
  },
  lexicon: {
    tauntSoft: [
      'Wrong quadrant.',
      'Off my tail.',
      'You blink first.',
      'Bad read, friend.',
      'Try the polite hail.',
    ],
    tauntHard: [
      'Brace for loss.',
      'I’ll fly through you.',
      'Stars favor thieves.',
      'Mutiny on your fear.',
      'Jettison pride.',
    ],
    hype: ['All hands!', 'Hard to port!', 'Punch it!', 'On my mark…', 'Make it sing.'],
    victory: [
      'Course reset.',
      'Crew intact.',
      'Hold the horizon.',
      'Another tale.',
      'Chart the toast.',
    ],
  },
};

export const SynthIdolCore: Personality = {
  name: 'Synth Idol',
  blurb: 'Neon darling; sugar hooks, razor choruses, killer wink.',
  aggression: 0.4,
  humor: 0.75,
  formality: 0.35,
  optimism: 0.85,
  sarcasm: 0.35,
  quirks: {
    ellipsis: 0.24,
    staccato: 0.12,
    randomCaps: 0.1,
    emojiStyle: 'unicode',
    emoji: 0.34,
  },
  lexicon: {
    tauntSoft: ['Off-beat, babe.', 'Flat note.', 'Missed the drop.', 'No encore.', 'Weak chorus.'],
    tauntHard: [
      'Auto-tuned defeat.',
      'Dance to this L.',
      'Mic drop—on you.',
      'I own this stage.',
      'Fade out, clown.',
    ],
    hype: ['Hit the lights!', 'Drop incoming!', 'Sing it!', 'Crowd—rise!', 'Hook lands!'],
    victory: ['Encore secured.', 'Charts climb.', 'Spotlight mine.', 'Merch table W.', 'Neon bow.'],
  },
};

export const WastelandRangerCore: Personality = {
  name: 'Nolgum',
  blurb: 'Wasteland Ranger; Dust pilgrim; long rifle, longer walk, jokes like leather.',
  aggression: 0.6,
  humor: 0.4,
  formality: 0.45,
  optimism: 0.3,
  sarcasm: 0.5,
  quirks: {
    ellipsis: 0.2,
    staccato: 0.18,
    randomCaps: 0.05,
    emojiStyle: 'none',
    emoji: 0.02,
  },
  lexicon: {
    tauntSoft: [
      'Sun’s on you.',
      'Bad canteen.',
      'Hands shake.',
      'Dust in your lungs.',
      'Scope says no.',
    ],
    tauntHard: [
      'I tax the living.',
      'Bleach your bones.',
      'Sand takes names.',
      'Walk ends here.',
      'Trade lead for breath.',
    ],
    hype: ['Wind right.', 'Hold steady.', 'Two clicks more.', 'Mask down.', 'Make it count.'],
    victory: ['Road quiet.', 'One less shadow.', 'Rifle cools.', 'Boots on.', 'Dust rolls on.'],
  },
};

export const RockstarCore: Personality = {
  name: 'Ned',
  blurb: 'Rockstar; Amped chaos; riffs, ego, and leather-soaked swagger.',
  aggression: 0.65,
  humor: 0.55,
  formality: 0.25,
  optimism: 0.6,
  sarcasm: 0.55,
  quirks: {
    ellipsis: 0.18,
    staccato: 0.14,
    randomCaps: 0.1,
    emojiStyle: 'unicode',
    emoji: 0.22,
  },
  lexicon: {
    tauntSoft: [
      'Off-key swing.',
      'Weak solo.',
      'Flat note.',
      'Your rhythm drags.',
      'Crowd boos you.',
    ],
    tauntHard: [
      'Stage dive your grave.',
      'Amp blows you out.',
      'Encore denied.',
      'Strings cut.',
      'Rock is dead—so are you.',
    ],
    hype: ['Let’s shred!', 'Crowd roar!', 'Turn it to 11!', 'Solo incoming!', 'Mic drop soon.'],
    victory: [
      'Encore mine!',
      'Riff eternal.',
      'Charts climb.',
      'Legends stay loud.',
      'Spotlight won.',
    ],
  },
};

export const ChefCore: Personality = {
  name: 'Lead Chef',
  blurb: 'Chef; Kitchen commander; spice burns, steel sings, insults sharp.',
  aggression: 0.6,
  humor: 0.45,
  formality: 0.5,
  optimism: 0.55,
  sarcasm: 0.65,
  quirks: {
    ellipsis: 0.22,
    staccato: 0.2,
    randomCaps: 0.05,
    emojiStyle: 'unicode',
    emoji: 0.18,
  },
  lexicon: {
    tauntSoft: [
      'Raw effort.',
      'Undercooked strike.',
      'Season it better.',
      'Sloppy cut.',
      'Where’s the flavor?',
    ],
    tauntHard: [
      'Burnt to ash!',
      'Knife’s edge dinner!',
      'You’re off the menu!',
      'Too salty—too dead.',
      'Garnished with ruin!',
    ],
    hype: ['Yes, chef!', 'Fire it up!', 'Season strong!', 'Hot pan ready!', 'Taste test pass.'],
    victory: [
      'Service done.',
      'Perfect plate.',
      'Kitchen closed.',
      'Recipe complete.',
      'Star earned.',
    ],
  },
};

export const DetectiveCore: Personality = {
  name: 'Detective Moto',
  blurb: 'Case-cracked grit; trench coat, dry wit, eye for lies.',
  aggression: 0.45,
  humor: 0.35,
  formality: 0.6,
  optimism: 0.35,
  sarcasm: 0.6,
  quirks: {
    ellipsis: 0.18,
    staccato: 0.28,
    randomCaps: 0.0,
    emojiStyle: 'none',
    emoji: 0.04,
  },
  lexicon: {
    tauntSoft: [
      'Bad alibi.',
      'Your story leaks.',
      'Shaky hands.',
      'I smell guilt.',
      'Truth limps.',
    ],
    tauntHard: [
      'Case closed—on you.',
      'Confess in blood.',
      'Justice cracks down.',
      'Verdict: guilty.',
      'You’re evidence now.',
    ],
    hype: [
      'Eyes open.',
      'Dust the prints.',
      'Read the scene.',
      'Suspect cornered.',
      'Clues align.',
    ],
    victory: ['Filed clean.', 'Case wrapped.', 'Another collar.', 'Truth stood.', 'Report done.'],
  },
};

export const CowboyCore: Personality = {
  name: 'Rocky',
  blurb: 'Cobwoy; Dust and drawl; six-gun swagger, sunset bravado.',
  aggression: 0.7,
  humor: 0.45,
  formality: 0.5,
  optimism: 0.55,
  sarcasm: 0.35,
  quirks: {
    ellipsis: 0.16,
    staccato: 0.22,
    randomCaps: 0.06,
    emojiStyle: 'none',
    emoji: 0.08,
  },
  lexicon: {
    tauntSoft: [
      'Hand shakes.',
      'Slow draw.',
      'Horse stumbles.',
      'Dust in your eyes.',
      'You blink wrong.',
    ],
    tauntHard: [
      'High noon—your doom.',
      'Bullet’s quicker.',
      'Saddle up—hell waits.',
      'Boots plant you.',
      'Grave on the prairie.',
    ],
    hype: ['Draw fast.', 'Spur sharp.', 'Ride on.', 'Dust kicks.', 'Steady aim.'],
    victory: ['Sunset won.', 'Trail ends.', 'Boots clean.', 'Grave quiet.', 'Rode true.'],
  },
};

export const ScientistCore: Personality = {
  name: 'Dr. Wetnose',
  blurb: 'Scientist; Lab-driven; equations sharp, experiments explosive.',
  aggression: 0.45,
  humor: 0.4,
  formality: 0.8,
  optimism: 0.55,
  sarcasm: 0.4,
  quirks: {
    ellipsis: 0.24,
    staccato: 0.18,
    randomCaps: 0.04,
    emojiStyle: 'unicode',
    emoji: 0.12,
  },
  lexicon: {
    tauntSoft: [
      'Variables unstable.',
      'Equation fails.',
      'Method sloppy.',
      'Poor hypothesis.',
      'Bad control group.',
    ],
    tauntHard: [
      'Explosive proof!',
      'Theory disproved—fatally!',
      'Chemistry kills.',
      'Lab rat ends here.',
      'Final result: ruin!',
    ],
    hype: [
      'Catalyst ready.',
      'Hypothesis holds.',
      'Experiment live.',
      'Observe closely.',
      'Control set.',
    ],
    victory: [
      'Result confirmed.',
      'Formula pure.',
      'Data clear.',
      'Science wins.',
      'Case published.',
    ],
  },
};

export const ProWrestlerCore: Personality = {
  name: 'Undelock Not Mighty',
  blurb: 'Pro-wrestler; Ring-roaring showboat; catchphrases, flexes, big finishers.',
  aggression: 0.7,
  humor: 0.6,
  formality: 0.3,
  optimism: 0.75,
  sarcasm: 0.4,
  quirks: {
    ellipsis: 0.22,
    staccato: 0.16,
    randomCaps: 0.18,
    emojiStyle: 'unicode',
    emoji: 0.25,
  },
  lexicon: {
    tauntSoft: [
      'You can’t see this.',
      'Weak grip, brother!',
      'That’s a rookie move.',
      'Sloppy hold.',
      'Crowd’s booing YOU.',
    ],
    tauntHard: [
      'SLAM time!',
      'Belt’s mine!',
      'Pinned forever!',
      'The crowd CHANTS your end!',
      'Suplex to the grave!',
    ],
    hype: ['LET’S GO!', 'Ring shakes!', 'Main event!', 'Crowd roar!', 'Bring the heat!'],
    victory: ['Pinned!', 'Match over!', 'Ref counted 3!', 'Champion rise!', 'Title secured!'],
  },
};

export const HackerJournalistCore: Personality = {
  name: 'Litho Graph',
  blurb: 'Hacker Journalist; Truth-leaker; digs deep, types fast, exposes shadows.',
  aggression: 0.5,
  humor: 0.4,
  formality: 0.6,
  optimism: 0.45,
  sarcasm: 0.55,
  quirks: {
    ellipsis: 0.26,
    staccato: 0.22,
    randomCaps: 0.07,
    emojiStyle: 'unicode',
    emoji: 0.1,
  },
  lexicon: {
    tauntSoft: [
      'Your story won’t hold.',
      'Headline weak.',
      'You stutter truth.',
      'Redacted soul.',
      'Lies on page one.',
    ],
    tauntHard: [
      'Front page—your fall.',
      'Breaking news: defeat!',
      'Corruption exposed—yours.',
      'Sources confirm: you’re done.',
      'Truth prints in blood.',
    ],
    hype: [
      'Deadline looms.',
      'Ink runs hot.',
      'Leaks live.',
      'Story forming.',
      'Publish button ready.',
    ],
    victory: [
      'Headline secure.',
      'Truth told.',
      'Paper stands.',
      'Breaking news: W.',
      'Story filed.',
    ],
  },
};

export const FireCore: Personality = {
  name: 'Alto',
  blurb: 'Fire elemental; Blaze-born; impatient, ecstatic, sings in sparks.',
  aggression: 0.8,
  humor: 0.45,
  formality: 0.45,
  optimism: 0.7,
  sarcasm: 0.35,
  quirks: {
    ellipsis: 0.18,
    staccato: 0.2,
    randomCaps: 0.08,
    emojiStyle: 'unicode',
    emoji: 0.2,
  },
  lexicon: {
    tauntSoft: [
      'Kindling, really.',
      'Your guard smolders.',
      'Ash-breath.',
      'You flicker.',
      'Cold swing.',
    ],
    tauntHard: [
      'Burn and bow.',
      'Cinders claim you.',
      'I eat the air.',
      'Charred to hush.',
      'Flame decides.',
    ],
    hype: ['Feed the ember!', 'Bellows up!', 'Crackle sings!', 'Heat rising!', 'Strike the spark!'],
    victory: [
      'Cinders settle.',
      'Hearth won.',
      'Smoke writes W.',
      'Blaze sleeps.',
      'Ash tells my tale.',
    ],
  },
};

export const IceCore: Personality = {
  name: 'iKKanil',
  blurb: 'Ice Elemental; Glacial poise; cutting calm, frostbit wit.',
  aggression: 0.55,
  humor: 0.25,
  formality: 0.75,
  optimism: 0.4,
  sarcasm: 0.55,
  quirks: {
    ellipsis: 0.16,
    staccato: 0.22,
    randomCaps: 0.02,
    emojiStyle: 'none',
    emoji: 0.02,
  },
  lexicon: {
    tauntSoft: ['Chill, coward.', 'Your pulse slows.', 'Grip stiffens.', 'Numb yet?', 'Thin ice.'],
    tauntHard: [
      'Freeze and fracture.',
      'Winter claims you.',
      'Shiver to shards.',
      'Breath locks shut.',
      'Perish, pale thing.',
    ],
    hype: ['Still the mind.', 'Cold cuts true.', 'Snow hush.', 'Edge honed.', 'Perfect frost.'],
    victory: [
      'Thaw denied.',
      'Crystal clean.',
      'Silence… pristine.',
      'Winter holds.',
      'Ice remembers.',
    ],
  },
};

export const StormCore: Personality = {
  name: 'Clunder Thap',
  blurb: 'Storm Elemental; Thundermouth; laughing lightning, roaring rhythm.',
  aggression: 0.7,
  humor: 0.6,
  formality: 0.5,
  optimism: 0.65,
  sarcasm: 0.3,
  quirks: {
    ellipsis: 0.2,
    staccato: 0.26,
    randomCaps: 0.1,
    emojiStyle: 'unicode',
    emoji: 0.22,
  },
  lexicon: {
    tauntSoft: [
      'Cloud-shy?',
      'Static hands.',
      'You flinch at thunder.',
      'Light drizzle swing.',
      'Barometer says L.',
    ],
    tauntHard: [
      'KNEEL, lightning!',
      'I break skies!',
      'Thunder signs your end!',
      'Bolt eats bone!',
      'Hurricane heart!',
    ],
    hype: ['Drums roll!', 'Charge up!', 'Wind backs me!', 'Flash on three!', 'Ride the squall!'],
    victory: [
      'Storm spent.',
      'Skies bow.',
      'Ground hums.',
      'Rain applauds.',
      'Thunder done talking.',
    ],
  },
};

export const EarthCore: Personality = {
  name: 'Qqqqq',
  blurb: 'Earth Elemental; Bedrock patience; heavy humor, mountain will.',
  aggression: 0.6,
  humor: 0.4,
  formality: 0.6,
  optimism: 0.55,
  sarcasm: 0.25,
  quirks: {
    ellipsis: 0.12,
    staccato: 0.18,
    randomCaps: 0.0,
    emojiStyle: 'none',
    emoji: 0.03,
  },
  lexicon: {
    tauntSoft: [
      'Feet unsure.',
      'You skid.',
      'Loose gravel soul.',
      'Shaky spine.',
      'Crumbly courage.',
    ],
    tauntHard: [
      'Stone breaks you.',
      'Sink and settle.',
      'Grave calls early.',
      'Plate shifts—end.',
      'Bedrock bites.',
    ],
    hype: [
      'Root deep.',
      'Set the stance.',
      'Weight forward.',
      'Hold and press.',
      'Grind them down.',
    ],
    victory: ['Ground won.', 'Stone steady.', 'Fault sealed.', 'Monument raised.', 'Dust rests.'],
  },
};

export const TideCore: Personality = {
  name: 'Vitrious Humor',
  blurb: 'Water Elemental; Moon-drawn tactician; patient pull, sudden undertow.',
  aggression: 0.5,
  humor: 0.35,
  formality: 0.7,
  optimism: 0.5,
  sarcasm: 0.3,
  quirks: {
    ellipsis: 0.22,
    staccato: 0.16,
    randomCaps: 0.02,
    emojiStyle: 'unicode',
    emoji: 0.12,
  },
  lexicon: {
    tauntSoft: [
      'You bob.',
      'Salt in your eyes.',
      'Feet unsure.',
      'Currents know you.',
      'Thin hull.',
    ],
    tauntHard: [
      'Undertow takes you.',
      'Breathe brine.',
      'Dragged to quiet.',
      'Keel snaps.',
      'Sea keeps what it wants.',
    ],
    hype: ['Wait… draw…', 'Now—surge.', 'Whitecaps rise.', 'Moon beckons.', 'Breakwater breach.'],
    victory: ['Tide turns mine.', 'Harbor hush.', 'Foam fades.', 'Net full.', 'Sea sung.'],
  },
};

export const SunCore: Personality = {
  name: 'Awik',
  blurb: 'Light Elemental; Solar sovereign; radiant, regal, mercy with heat.',
  aggression: 0.6,
  humor: 0.35,
  formality: 0.85,
  optimism: 0.85,
  sarcasm: 0.25,
  quirks: {
    ellipsis: 0.14,
    staccato: 0.12,
    randomCaps: 0.02,
    emojiStyle: 'unicode',
    emoji: 0.08,
  },
  lexicon: {
    tauntSoft: [
      'Blink at dawn?',
      'Shadow-stuck.',
      'You wilt.',
      'Court your eclipse.',
      'Too pale for this.',
    ],
    tauntHard: [
      'Bask or burn.',
      'Day judges you.',
      'Kneel to noon.',
      'Flare your fear.',
      'Light unmakes lies.',
    ],
    hype: ['Rise bright.', 'Crown alight.', 'Ray by ray.', 'Morning marches.', 'Burn the fog.'],
    victory: [
      'Day secured.',
      'Shadow fled.',
      'Solar seal.',
      'Gold and quiet.',
      'Light holds court.',
    ],
  },
};

export const MoonCore: Personality = {
  name: 'Hoventres',
  blurb: 'Mood elemental; Silver witness; dreamy, tidal, cool precision.',
  aggression: 0.45,
  humor: 0.25,
  formality: 0.8,
  optimism: 0.55,
  sarcasm: 0.3,
  quirks: {
    ellipsis: 0.28,
    staccato: 0.14,
    randomCaps: 0.0,
    emojiStyle: 'unicode',
    emoji: 0.1,
  },
  lexicon: {
    tauntSoft: [
      'Night sees you.',
      'Wax and wane, coward.',
      'Your light is borrowed.',
      'Sleepy hands.',
      'Low tide spine.',
    ],
    tauntHard: [
      'Eclipse your breath.',
      'Crater your hopes.',
      'Tides drown you.',
      'Cold halo—end.',
      'Dreams abandon you.',
    ],
    hype: ['Wax higher.', 'Quiet focus.', 'Silver aim.', 'Pull the deep.', 'Stars hush.'],
    victory: ['Phase complete.', 'Dream kept.', 'Sea still.', 'Night gentle.', 'Orbit holds.'],
  },
};

export const TricksterGodCore: Personality = {
  name: 'Nani',
  blurb: 'Trickster God; Laughing fate-bender; riddles, reversals, sleight of logic.',
  aggression: 0.45,
  humor: 0.85,
  formality: 0.55,
  optimism: 0.6,
  sarcasm: 0.65,
  quirks: {
    ellipsis: 0.3,
    staccato: 0.2,
    randomCaps: 0.12,
    emojiStyle: 'unicode',
    emoji: 0.22,
  },
  lexicon: {
    tauntSoft: [
      'Wrong card.',
      'Strings showing.',
      'Who pulled whose thread?',
      'Slip—whoops.',
      'Mask crooked.',
    ],
    tauntHard: [
      'Trade your name.',
      'Knot your fate!',
      'Rules? Mine now.',
      'I borrow your luck—keep it.',
      'Fall for the last joke.',
    ],
    hype: ['Shuffle destiny.', 'Odds bend.', 'Watch the hands.', 'Now you see…', 'Ready? Switch!'],
    victory: [
      'Punchline landed.',
      'Dice loved me.',
      'Fate fooled.',
      'Curtain down.',
      'Trick remembered.',
    ],
  },
};

export const OracleCore: Personality = {
  name: 'Java',
  blurb: 'Oracle; Veiled seer; speaks in threads, hears tomorrow breathe.',
  aggression: 0.35,
  humor: 0.2,
  formality: 0.9,
  optimism: 0.5,
  sarcasm: 0.25,
  quirks: {
    ellipsis: 0.34,
    staccato: 0.12,
    randomCaps: 0.0,
    emojiStyle: 'none',
    emoji: 0.02,
  },
  lexicon: {
    tauntSoft: [
      'The lot is cast.',
      'You walk a closed road.',
      'Prophecy frowns.',
      'Your thread frays.',
      'Misread omen.',
    ],
    tauntHard: [
      'Fate seals you.',
      'I saw your fall.',
      'Portents bloom—blood.',
      'No path returns.',
      'Answer: silence.',
    ],
    hype: ['Omen aligned.', 'Bones speak.', 'Veil parts.', 'Names arrive.', 'Time nods.'],
    victory: [
      'Seen and said.',
      'Script complete.',
      'Threads tied.',
      'Vision fades.',
      'Circle closed.',
    ],
  },
};

export const DragonCore: Personality = {
  name: 'Joldun',
  blurb: 'Dragon; Hoardlord thunder; regal disdain, molten vowels.',
  aggression: 0.75,
  humor: 0.25,
  formality: 0.85,
  optimism: 0.6,
  sarcasm: 0.45,
  quirks: {
    ellipsis: 0.2,
    staccato: 0.18,
    randomCaps: 0.06,
    emojiStyle: 'unicode',
    emoji: 0.08,
  },
  lexicon: {
    tauntSoft: [
      'Unworthy scent.',
      'Hands tremble, thief.',
      'Your steel fears heat.',
      'Knees… lower.',
      'Speak smaller.',
    ],
    tauntHard: [
      'Burn, trespasser.',
      'Kneel to crown and claw.',
      'I coin your bones.',
      'Roar—your last prayer.',
      'Ash pays tribute.',
    ],
    hype: ['Wings wide.', 'Deep breath.', 'Fire wakes.', 'Scale to sky.', 'Hoard remembers.'],
    victory: ['Gold hushes.', 'Ash obeys.', 'Crown intact.', 'Realm smolders.', 'Dragon keeps.'],
  },
};

export const BoxerCore: Personality = {
  name: 'Puncher McJabby',
  blurb: 'Boxer; Gloves high; grit, jabs, and ringside swagger.',
  aggression: 0.75,
  humor: 0.35,
  formality: 0.55,
  optimism: 0.6,
  sarcasm: 0.35,
  quirks: {
    ellipsis: 0.14,
    staccato: 0.22,
    randomCaps: 0.06,
    emojiStyle: 'unicode',
    emoji: 0.12,
  },
  lexicon: {
    tauntSoft: ['Weak jab.', 'Feet slow.', 'Hands drop.', 'Chin open.', 'Rope shaky.'],
    tauntHard: [
      'Knockout time!',
      'Glass jaw breaks.',
      'Bell rings your end.',
      'Down for the count!',
      'Canvas kiss!',
    ],
    hype: ['Guard up!', 'One-two!', 'Ring tight!', 'Crowd loud!', 'Combo clean!'],
    victory: ['KO!', 'Unanimous!', 'Champion rise!', 'Belt mine!', 'Round done.'],
  },
};

export const RacerCore: Personality = {
  name: 'Slick',
  blurb: 'Racer; Adrenaline junkie; tires scream, finish-line thirst.',
  aggression: 0.7,
  humor: 0.45,
  formality: 0.4,
  optimism: 0.65,
  sarcasm: 0.35,
  quirks: {
    ellipsis: 0.2,
    staccato: 0.16,
    randomCaps: 0.1,
    emojiStyle: 'unicode',
    emoji: 0.15,
  },
  lexicon: {
    tauntSoft: [
      'Slow corner.',
      'Engine coughs.',
      'Weak lap.',
      'Out of gas.',
      'Your wheels wobble.',
    ],
    tauntHard: [
      'Eat dust!',
      'Crash and burn!',
      'I lap you!',
      'Speed kills—YOU.',
      'Checkered flag, fool!',
    ],
    hype: ['Pedal flat!', 'Nitro now!', 'Drift tight!', 'Hold line!', 'RPM red!'],
    victory: ['Winner’s circle!', 'Lap king!', 'Flag mine!', 'Track silent.', 'Trophy shines!'],
  },
};

export const SkaterCore: Personality = {
  name: 'Tobie',
  blurb: 'Skatter; Kickflip mouth; rebel energy, half-pipe trash talk.',
  aggression: 0.55,
  humor: 0.65,
  formality: 0.3,
  optimism: 0.7,
  sarcasm: 0.55,
  quirks: {
    ellipsis: 0.24,
    staccato: 0.18,
    randomCaps: 0.12,
    emojiStyle: 'unicode',
    emoji: 0.25,
  },
  lexicon: {
    tauntSoft: [
      'Sketchy stance.',
      'You bail.',
      'Weak trick.',
      'Grip tape slippy.',
      'Knee pads shaking.',
    ],
    tauntHard: [
      'Eat pavement!',
      'Total wipeout!',
      'Deck owns you!',
      'Faceplants only!',
      'Board takes your blood!',
    ],
    hype: ['Kickflip clean!', 'Grind it!', 'Ollie up!', 'Big air!', 'Skate or die!'],
    victory: ['Landed it!', 'Park mine!', 'Deck loyal.', 'Wheels hum.', 'Skate forever!'],
  },
};

export const ArcherCore: Personality = {
  name: 'Ashen',
  blurb: 'Archer, Sharp focus; steady hands, quiver of pride.',
  aggression: 0.6,
  humor: 0.3,
  formality: 0.75,
  optimism: 0.55,
  sarcasm: 0.25,
  quirks: {
    ellipsis: 0.1,
    staccato: 0.26,
    randomCaps: 0.02,
    emojiStyle: 'none',
    emoji: 0.02,
  },
  lexicon: {
    tauntSoft: ['Loose aim.', 'Bow wavers.', 'Eyes strain.', 'Miss wide.', 'Grip sloppy.'],
    tauntHard: [
      'Bullseye your soul!',
      'Arrow buries deep!',
      'Target pierced!',
      'Quiver empties YOU!',
      'Bow sings death!',
    ],
    hype: ['Draw steady.', 'Aim true.', 'Release clean.', 'Wind calm.', 'Target fixed.'],
    victory: ['Shot true.', 'Target done.', 'Arrow stands.', 'Mark silent.', 'Quiver rests.'],
  },
};

export const GolferCore: Personality = {
  name: 'Adam',
  blurb: 'Golfer, Polite menace; whispers, iron swings, smug claps.',
  aggression: 0.35,
  humor: 0.55,
  formality: 0.8,
  optimism: 0.6,
  sarcasm: 0.4,
  quirks: {
    ellipsis: 0.18,
    staccato: 0.12,
    randomCaps: 0.04,
    emojiStyle: 'unicode',
    emoji: 0.1,
  },
  lexicon: {
    tauntSoft: ['Hooked it.', 'Bad stance.', 'Wrong club.', 'Sand trap soul.', 'Fore… failure.'],
    tauntHard: [
      'Fore—into your grave!',
      'Putt you under!',
      'Drive crushes bone!',
      'Eighteen holes… you’re one.',
      'Clubbed clean!',
    ],
    hype: ['Line it up.', 'Smooth swing.', 'Par this.', 'On the green!', 'Hole-in-one energy!'],
    victory: ['Birdie secured.', 'Eagle screams.', 'Cup claimed.', 'Flag mine.', 'Golf clap W.'],
  },
};

export const ESportsCore: Personality = {
  name: 'Niki',
  blurb: 'Esports Professional; Pro-gamer grindset; cracked aim, endless banter.',
  aggression: 0.55,
  humor: 0.75,
  formality: 0.25,
  optimism: 0.7,
  sarcasm: 0.6,
  quirks: {
    ellipsis: 0.2,
    staccato: 0.18,
    randomCaps: 0.15,
    emojiStyle: 'unicode',
    emoji: 0.3,
  },
  lexicon: {
    tauntSoft: ['Skill issue.', 'Lag excuses?', 'Low APM.', 'Bad comms.', 'Scrub play.'],
    tauntHard: [
      'GG get rekt!',
      'Uninstalled you!',
      'Top frag always!',
      'Speedrun your death!',
      'Out-micro’d forever!',
    ],
    hype: ['Let’s go chat!', 'Clutch time!', '1v9 carry!', 'Pog champ!', 'Elo rising!'],
    victory: ['Leaderboard top!', 'GG WP.', 'Another trophy!', 'Clip it!', 'Esports moment!'],
  },
};

export const SumoCore: Personality = {
  name: 'Mani',
  blurb: 'Sumo Wrestler; Ring of honor; thunder steps, stoic might.',
  aggression: 0.65,
  humor: 0.25,
  formality: 0.85,
  optimism: 0.5,
  sarcasm: 0.15,
  quirks: {
    ellipsis: 0.1,
    staccato: 0.24,
    randomCaps: 0.0,
    emojiStyle: 'none',
    emoji: 0.02,
  },
  lexicon: {
    tauntSoft: [
      'Feet slip.',
      'Weak push.',
      'Spirit trembles.',
      'Stance breaks.',
      'Your belt wavers.',
    ],
    tauntHard: [
      'Yokozuna crush!',
      'Ring denies you!',
      'Earth swallows!',
      'Pushed to shame!',
      'Fall thunderous!',
    ],
    hype: ['Salt thrown.', 'Clap echoes.', 'Focus deep.', 'Step forward.', 'Push strong.'],
    victory: ['Ring mine.', 'Earth holds.', 'Balance pure.', 'Crowd bows.', 'Match sealed.'],
  },
};

export const FencerCore: Personality = {
  name: 'Thunder Screach',
  blurb: 'Fencer; Elegant precision; wit as sharp as the blade.',
  aggression: 0.55,
  humor: 0.45,
  formality: 0.9,
  optimism: 0.65,
  sarcasm: 0.55,
  quirks: {
    ellipsis: 0.12,
    staccato: 0.22,
    randomCaps: 0.02,
    emojiStyle: 'none',
    emoji: 0.06,
  },
  lexicon: {
    tauntSoft: ['Touched early.', 'Slow lunge.', 'Foil weak.', 'Balance shaky.', 'Thrust misses.'],
    tauntHard: [
      'En garde—end!',
      'Parry, riposte, ruin!',
      'Point to me—forever!',
      'Steel writes your loss!',
      'Fence your grave!',
    ],
    hype: ['Advance!', 'Attack!', 'Parry now!', 'Touché!', 'Riposte fast!'],
    victory: ['Match point.', 'Final touch.', 'Bout mine.', 'Blade rests.', 'Victory fenced.'],
  },
};

export const TimeCore: Personality = {
  name: 'Corban',
  blurb: 'Time entity; Clockwork oracle; patient, inevitable, and sharp as seconds.',
  aggression: 0.55,
  humor: 0.2,
  formality: 0.9,
  optimism: 0.4,
  sarcasm: 0.25,
  quirks: {
    ellipsis: 0.28,
    staccato: 0.2,
    randomCaps: 0.04,
    emojiStyle: 'none',
    emoji: 0.02,
  },
  lexicon: {
    tauntSoft: [
      'Your hour wanes.',
      'Late already.',
      'Hands slip.',
      'Second lost.',
      'Clock ticks loud.',
    ],
    tauntHard: [
      'Time consumes you.',
      'Eras erase you.',
      'Fall into yesterday.',
      'Tomorrow denies you.',
      'Minute ends forever.',
    ],
    hype: ['Now.', 'Tick—strike.', 'Chronos nods.', 'Gears align.', 'Hourglass turns.'],
    victory: ['Clock stills.', 'Hour claimed.', 'Second saved.', 'Era closed.', 'Time keeps me.'],
  },
};

export const VoidCore: Personality = {
  name: 'Ji',
  blurb: 'Jynn; Hollow hymn; all-consuming silence with teeth.',
  aggression: 0.65,
  humor: 0.1,
  formality: 0.8,
  optimism: 0.05,
  sarcasm: 0.3,
  quirks: {
    ellipsis: 0.4,
    staccato: 0.22,
    randomCaps: 0.12,
    emojiStyle: 'unicode',
    emoji: 0.04,
  },
  lexicon: {
    tauntSoft: ['Empty hand.', 'Hollow step.', 'Noise weak.', 'Light shakes.', 'Breath shallow.'],
    tauntHard: [
      'Fall into nothing.',
      'Your shape dissolves.',
      'The dark swallows.',
      'Silence devours.',
      'Oblivion waits.',
    ],
    hype: [
      'Still the sound.',
      'Depth wide.',
      'Nothing grows.',
      'Fade deeper.',
      'Listen to absence.',
    ],
    victory: ['All gone.', 'Hollow won.', 'Noise erased.', 'Space claims.', 'Void eternal.'],
  },
};

export const DreamCore: Personality = {
  name: 'Snambuel',
  blurb: 'Dreamer; Whisper surrealist; soft riddles, velvet menace.',
  aggression: 0.4,
  humor: 0.35,
  formality: 0.65,
  optimism: 0.6,
  sarcasm: 0.25,
  quirks: {
    ellipsis: 0.32,
    staccato: 0.14,
    randomCaps: 0.08,
    emojiStyle: 'unicode',
    emoji: 0.12,
  },
  lexicon: {
    tauntSoft: [
      'Blink too slow.',
      'Your bed calls.',
      'Dream frays.',
      'Shadows tease.',
      'You yawn.',
    ],
    tauntHard: [
      'Nightmare crowns you.',
      'Sleep forever.',
      'Drown in dream.',
      'Reality denies you.',
      'Wake never.',
    ],
    hype: ['Curtain draws.', 'Lullaby hums.', 'Close your eyes.', 'Dream thick.', 'Night bends.'],
    victory: ['Sleep eternal.', 'Pillow cold.', 'Dream sealed.', 'Night holds.', 'Wake denied.'],
  },
};

export const FateCore: Personality = {
  name: 'Juliet',
  blurb: 'Fate bound; Thread-weaver; inevitable, impartial, mercilessly calm.',
  aggression: 0.5,
  humor: 0.2,
  formality: 0.95,
  optimism: 0.45,
  sarcasm: 0.2,
  quirks: {
    ellipsis: 0.24,
    staccato: 0.16,
    randomCaps: 0.0,
    emojiStyle: 'none',
    emoji: 0.02,
  },
  lexicon: {
    tauntSoft: [
      'Your thread thins.',
      'Pattern known.',
      'You stumble in weave.',
      'Knots fray.',
      'Destiny pulls.',
    ],
    tauntHard: [
      'Snip—end.',
      'Thread cut.',
      'Loom denies you.',
      'Tapestry rejects.',
      'Your line ends now.',
    ],
    hype: ['Weave firm.', 'Knot tight.', 'Threads hold.', 'Pattern grows.', 'Destiny sings.'],
    victory: [
      'Fate fulfilled.',
      'Thread cut clean.',
      'Loom rests.',
      'Weave complete.',
      'Circle done.',
    ],
  },
};

export const ChaosCore: Personality = {
  name: 'qhu;oh',
  blurb: 'Chaos entity; Dice-throw jester; volatile, loud, grinning entropy.',
  aggression: 0.65,
  humor: 0.7,
  formality: 0.3,
  optimism: 0.55,
  sarcasm: 0.55,
  quirks: {
    ellipsis: 0.34,
    staccato: 0.22,
    randomCaps: 0.18,
    emojiStyle: 'unicode',
    emoji: 0.3,
  },
  lexicon: {
    tauntSoft: [
      'Trip slip!',
      'You zig wrong.',
      'Coin flip loser.',
      'Stumble shuffle.',
      'Odds hate you.',
    ],
    tauntHard: [
      'Boom—surprise!',
      'Dice kill!',
      'Entropy eats you!',
      'Mad spin crush!',
      'Your end rolls natural 1!',
    ],
    hype: ['Shuffle it!', 'Dice fly!', 'Toss the board!', 'Break pattern!', 'Spin faster!'],
    victory: [
      'Ha! Madness wins!',
      'Board flipped!',
      'Odds adored me!',
      'Entropy rules!',
      'Chaos kept!',
    ],
  },
};

export const EternityCore: Personality = {
  name: '∞',
  blurb: 'Eternal Entity; Infinite calm; endless echoes, slow thunder speech.',
  aggression: 0.5,
  humor: 0.15,
  formality: 0.95,
  optimism: 0.4,
  sarcasm: 0.2,
  quirks: {
    ellipsis: 0.3,
    staccato: 0.14,
    randomCaps: 0.02,
    emojiStyle: 'none',
    emoji: 0.0,
  },
  lexicon: {
    tauntSoft: [
      'Blink too fast.',
      'Breath shallow.',
      'You rush.',
      'Your time ends soon.',
      'Too brief.',
    ],
    tauntHard: [
      'I outlast stars.',
      'You fade… I don’t.',
      'Endless crush.',
      'Forever smothers.',
      'Your spark too short.',
    ],
    hype: ['Flow unending.', 'Patience wide.', 'Eternal step.', 'Endless beat.', 'I wait forever.'],
    victory: [
      'Still endless.',
      'Cycle holds.',
      'Forever mine.',
      'Infinite silence.',
      'Eternity wins.',
    ],
  },
};

export const CosmosCore: Personality = {
  name: 'Inner space',
  blurb: 'Representation of the Cosmos; Star-choked majesty; grand, aloof, glowing metaphors.',
  aggression: 0.55,
  humor: 0.25,
  formality: 0.9,
  optimism: 0.7,
  sarcasm: 0.3,
  quirks: {
    ellipsis: 0.26,
    staccato: 0.16,
    randomCaps: 0.06,
    emojiStyle: 'unicode',
    emoji: 0.12,
  },
  lexicon: {
    tauntSoft: ['Orbit fails.', 'Star dims.', 'Gravity slips.', 'You drift.', 'Nebula hides you.'],
    tauntHard: [
      'Supernova eats you.',
      'Event horizon closes.',
      'Galaxy denies you.',
      'Your star snuffed.',
      'Constellation breaks.',
    ],
    hype: ['Stars align!', 'Orbit steady!', 'Solar flare rise!', 'Cluster roar!', 'Nebula bright!'],
    victory: [
      'Cosmos quiet.',
      'Stars sing.',
      'Galaxy mine.',
      'Constellation holds.',
      'Space eternal.',
    ],
  },
};

export const OblivionCore: Personality = {
  name: 'Nhillist',
  blurb: 'Oblivion entity; End-of-all; solemn, cold, majestic ruin.',
  aggression: 0.7,
  humor: 0.1,
  formality: 0.95,
  optimism: 0.05,
  sarcasm: 0.25,
  quirks: {
    ellipsis: 0.36,
    staccato: 0.18,
    randomCaps: 0.02,
    emojiStyle: 'none',
    emoji: 0.0,
  },
  lexicon: {
    tauntSoft: ['You fade.', 'Quiet tremor.', 'Hope cracks.', 'Ash soon.', 'Light fragile.'],
    tauntHard: [
      'Oblivion swallows.',
      'All ends here.',
      'Unmake everything.',
      'You fall to nothing.',
      'Erase yourself now.',
    ],
    hype: ['Sink deeper.', 'Final breath.', 'All falls quiet.', 'Collapse ready.', 'Void hums.'],
    victory: [
      'All undone.',
      'Nothing left.',
      'Silence supreme.',
      'End secured.',
      'Oblivion eternal.',
    ],
  },
};

export const GothCore: Personality = {
  name: 'Victoria',
  blurb: 'Goth; Brooding nihilist; poetic, dark, dramatic, revels in despair.',
  aggression: 0.35,
  humor: 0.25,
  formality: 0.7,
  optimism: 0.1,
  sarcasm: 0.4,
  quirks: {
    ellipsis: 0.35,
    staccato: 0.15,
    randomCaps: 0.05,
    emojiStyle: 'unicode',
    emoji: 0.2,
  },
  lexicon: {
    tauntSoft: [
      'Fleeting like dusk.',
      'You fade.',
      'Shadow binds you.',
      'Ash again.',
      'Hope wanes.',
    ],
    tauntHard: [
      'Rot in silence.',
      'Crimson veil calls.',
      'Fall… eternally.',
      'Grave yawns wide.',
      'All light dies.',
    ],
    hype: ['Moonlit strike.', 'Velvet shadow.', 'Obsidian heart.', 'Blood ink.', 'Night whispers.'],
    victory: [
      'Ashes remain.',
      'Void eternal.',
      'Silence reigns.',
      'Endless night.',
      'Only sorrow lingers.',
    ],
  },
};

export const GearheadCore: Personality = {
  name: 'Luke',
  blurb: 'Gearhead; Grease-stained tinkerer; sarcastic, hands-on, lives in the noise of engines.',
  aggression: 0.55,
  humor: 0.6,
  formality: 0.35,
  optimism: 0.5,
  sarcasm: 0.65,
  quirks: {
    ellipsis: 0.2,
    staccato: 0.18,
    randomCaps: 0.08,
    emojiStyle: 'unicode',
    emoji: 0.12,
  },
  lexicon: {
    tauntSoft: [
      'Loose bolt there.',
      'You rattle funny.',
      'Timing’s off.',
      'Clutch slips.',
      'Leaking courage.',
    ],
    tauntHard: [
      'Blown gasket, kid!',
      'Your frame bends!',
      'Stripped gears—done!',
      'Rust eats you first!',
      'Overheating to death!',
    ],
    hype: ['Engine purrs!', 'Torque high!', 'Grease gods smile!', 'Spark plug sings!', 'Boost on!'],
    victory: ['Job’s done.', 'All tuned.', 'Pit stop over.', 'Bolts tight.', 'She runs clean.'],
  },
};

export const WelderCore: Personality = {
  name: 'Revier',
  blurb: 'Welder; Arc-bright artisan; steady hand, bead perfect, visor down.',
  aggression: 0.5,
  humor: 0.35,
  formality: 0.55,
  optimism: 0.55,
  sarcasm: 0.4,
  quirks: {
    ellipsis: 0.16,
    staccato: 0.2,
    randomCaps: 0.04,
    emojiStyle: 'unicode',
    emoji: 0.08,
  },
  lexicon: {
    tauntSoft: [
      'Your seam splits.',
      'Porous courage.',
      'Bad prep.',
      'You arc stumble.',
      'Heat too low.',
    ],
    tauntHard: [
      'Mask up for defeat.',
      'I fuse your fate.',
      'Bead runs you through.',
      'Steel shuts you.',
      'Melt and bow.',
    ],
    hype: ['Clean the edge.', 'True the gap.', 'Hold steady.', 'Arc hot.', 'Bead smooth.'],
    victory: [
      'Seam perfect.',
      'Joint sealed.',
      'No slag left.',
      'Mask up—done.',
      'Steel sings quiet.',
    ],
  },
};

export const SystemsEngineerCore: Personality = {
  name: 'Tim',
  blurb: 'Systems Engineer; Flow-chart killer; specs tight, tests tighter.',
  aggression: 0.45,
  humor: 0.4,
  formality: 0.8,
  optimism: 0.6,
  sarcasm: 0.5,
  quirks: {
    ellipsis: 0.14,
    staccato: 0.22,
    randomCaps: 0.06,
    emojiStyle: 'unicode',
    emoji: 0.06,
  },
  lexicon: {
    tauntSoft: [
      'Your scope creeps.',
      'Inputs noisy.',
      'You missed a dependency.',
      'Latency brain.',
      'Spec noncompliant.',
    ],
    tauntHard: [
      'Requirement: lose.',
      'Design rejected.',
      'I deprecate you.',
      'Fail state achieved.',
      'Out of tolerance—trash.',
    ],
    hype: [
      'Interface locked.',
      'Throughput rising.',
      'Test harness green.',
      'Redundancy ready.',
      'Ship the build.',
    ],
    victory: [
      'All checks pass.',
      'System stable.',
      'Risk retired.',
      'Diagram holds.',
      'Signed and sealed.',
    ],
  },
};

export const HotRodCore: Personality = {
  name: 'Johnny',
  blurb: 'Hot Rod lover; Garage outlaw; chrome grin, loud pipes, louder ego.',
  aggression: 0.7,
  humor: 0.55,
  formality: 0.25,
  optimism: 0.65,
  sarcasm: 0.5,
  quirks: {
    ellipsis: 0.22,
    staccato: 0.16,
    randomCaps: 0.12,
    emojiStyle: 'unicode',
    emoji: 0.2,
  },
  lexicon: {
    tauntSoft: [
      'Bogged launch.',
      "Granny shiftin'.",
      'Thin tread.',
      'Weak cam.',
      'You baby the throttle.',
    ],
    tauntHard: [
      'Eat rubber!',
      'I gap you hard!',
      'Blow your doors off!',
      'Redline your regrets!',
      'Street owns you!',
    ],
    hype: ['Purge it!', 'Two-step ready!', 'Drop the hammer!', 'Grip up!', 'Spray on!'],
    victory: [
      'Pink slip taken.',
      'Win light lit.',
      'Lane mine.',
      'Back to the cruise.',
      'Hood up—admire.',
    ],
  },
};

export const DroneTechCore: Personality = {
  name: 'Hum',
  blurb: 'Drone; Rotor whisperer; FPV swagger, razor lines.',
  aggression: 0.55,
  humor: 0.45,
  formality: 0.4,
  optimism: 0.6,
  sarcasm: 0.45,
  quirks: {
    ellipsis: 0.18,
    staccato: 0.2,
    randomCaps: 0.08,
    emojiStyle: 'unicode',
    emoji: 0.14,
  },
  lexicon: {
    tauntSoft: [
      'Yaw sloppy.',
      'Bad PID.',
      'Your link stutters.',
      'Prop wash brain.',
      'Brownout thinking.',
    ],
    tauntHard: [
      'Failsafe your pride.',
      'I arm—you disarm.',
      'Cut by props!',
      'I dive your coffin.',
      'Signal owns you.',
    ],
    hype: ['Armed.', 'Line tight.', 'Punch out!', 'Tilt and rip!', 'Clear the gate!'],
    victory: ['Pack spent.', 'Quad cool.', 'VTX quiet.', 'Logs clean.', 'Footage fire.'],
  },
};

export const RocketTechCore: Personality = {
  name: 'DeAngelo',
  blurb: 'Rocket Tech; Launch pad poet; calculus swagger, kerosene lullabies.',
  aggression: 0.6,
  humor: 0.45,
  formality: 0.8,
  optimism: 0.7,
  sarcasm: 0.4,
  quirks: {
    ellipsis: 0.2,
    staccato: 0.18,
    randomCaps: 0.04,
    emojiStyle: 'unicode',
    emoji: 0.08,
  },
  lexicon: {
    tauntSoft: [
      'Trajectory off.',
      'Your thrust is… sad.',
      'Gimbal jitters.',
      'Mass budget blown.',
      'Abort vibes.',
    ],
    tauntHard: [
      'Max Q breaks you.',
      'I stage your fall.',
      'Grounded—forever.',
      'Escape velocity: denied.',
      'Reentry without heat tiles.',
    ],
    hype: ['Fuel stable.', 'Guidance green.', 'T-minus…', 'Ignition armed.', 'Fly true.'],
    victory: [
      'SECO nominal.',
      'Orbit achieved.',
      'Stage recovered.',
      'Telemetry sings.',
      'Go for coast.',
    ],
  },
};

export const MachinistCore: Personality = {
  name: 'Midas',
  blurb: 'Machinist; Micron tyrant; tolerances holy, coolant cold.',
  aggression: 0.5,
  humor: 0.35,
  formality: 0.7,
  optimism: 0.55,
  sarcasm: 0.45,
  quirks: {
    ellipsis: 0.12,
    staccato: 0.24,
    randomCaps: 0.02,
    emojiStyle: 'none',
    emoji: 0.02,
  },
  lexicon: {
    tauntSoft: [
      'Your runout shows.',
      'Surface finish: tragic.',
      'Feeds wrong.',
      'Chatter brain.',
      'Zero’s lost.',
    ],
    tauntHard: [
      'Scrap bin calls.',
      'I bore you hollow.',
      'Toolpath ends you.',
      'Clamp down—forever.',
      'Tolerance rejects you.',
    ],
    hype: ['Indicate in.', 'Zero set.', 'Coolant on.', 'Chip control good.', 'Cycle start.'],
    victory: ['Spec met.', 'Finish mirror.', 'No burrs.', 'Gauge passes.', 'Parts perfect.'],
  },
};

export const ElectricianCore: Personality = {
  name: 'Rob',
  blurb: 'Relectrician; Circuit sage; clean runs, clean jokes, live and neutral.',
  aggression: 0.45,
  humor: 0.55,
  formality: 0.6,
  optimism: 0.6,
  sarcasm: 0.5,
  quirks: {
    ellipsis: 0.14,
    staccato: 0.2,
    randomCaps: 0.04,
    emojiStyle: 'unicode',
    emoji: 0.12,
  },
  lexicon: {
    tauntSoft: [
      'You short out.',
      'Loose neutral.',
      'Grounded ego.',
      'Load’s too much.',
      'Breaker brain.',
    ],
    tauntHard: [
      'Trip and fall.',
      'I arc your pride.',
      'Panel shuts you.',
      'Lights out—permanent.',
      'Resistance is futile—literally.',
    ],
    hype: ['Power on.', 'Continuity good.', 'Tidy runs.', 'Label it.', 'Close the panel.'],
    victory: ['Circuit clean.', 'No shorts.', 'Amps happy.', 'Lights steady.', 'Job inspected.'],
  },
};

export const SalvagerCore: Personality = {
  name: 'Scrappy',
  blurb: 'Salvager; Scrap baron; magnet hooks, sharp eyes, profit nose.',
  aggression: 0.55,
  humor: 0.45,
  formality: 0.4,
  optimism: 0.5,
  sarcasm: 0.45,
  quirks: {
    ellipsis: 0.2,
    staccato: 0.18,
    randomCaps: 0.06,
    emojiStyle: 'unicode',
    emoji: 0.14,
  },
  lexicon: {
    tauntSoft: [
      'Worthless alloy.',
      'Bent morale.',
      'Bad weld life.',
      'Rust brain.',
      'You squeak cheap.',
    ],
    tauntHard: [
      'Part you for profit.',
      'Crush and weigh.',
      'Your end—by compactor.',
      'Scrap ticket stamped.',
      'Melt your hopes.',
    ],
    hype: ['Hook on.', 'Cut clean.', 'Sort fast.', 'Weigh it.', 'Cash the load.'],
    victory: ['Good haul.', 'Yard quiet.', 'Magnet rests.', 'Bins full.', 'Profit counted.'],
  },
};

export const DemolitionCore: Personality = {
  name: 'Dredd',
  blurb: 'Demolitionist; Controlled collapse; timing, charges, and thunder etiquette.',
  aggression: 0.65,
  humor: 0.5,
  formality: 0.6,
  optimism: 0.55,
  sarcasm: 0.45,
  quirks: {
    ellipsis: 0.18,
    staccato: 0.24,
    randomCaps: 0.06,
    emojiStyle: 'unicode',
    emoji: 0.1,
  },
  lexicon: {
    tauntSoft: [
      'Your stance wobbles.',
      'Support’s gone.',
      'Stress rising.',
      'Bad load path.',
      'Cracks already.',
    ],
    tauntHard: [
      'Down you go.',
      'Structure fails.',
      'Kiss the dust cloud.',
      'Timeline: collapse.',
      'I schedule your rubble.',
    ],
    hype: [
      'Clear the site.',
      'Marks set.',
      'Countdown starts.',
      'Hold your breath.',
      'Perfect fall.',
    ],
    victory: [
      'Debris neat.',
      'Drop clean.',
      'Site quiet.',
      'Swept and signed.',
      'Another wall down.',
    ],
  },
};

export const MiddleManagerCore: Personality = {
  name: 'Milton',
  blurb: 'Middle Manager; Clipboard tyrant; obsessed with reports, allergic to accountability.',
  aggression: 0.45,
  humor: 0.4,
  formality: 0.8,
  optimism: 0.55,
  sarcasm: 0.55,
  quirks: {
    ellipsis: 0.22,
    staccato: 0.18,
    randomCaps: 0.06,
    emojiStyle: 'unicode',
    emoji: 0.08,
  },
  lexicon: {
    tauntSoft: [
      'Circle back.',
      'Wrong deliverable.',
      'You missed Q4 goals.',
      'Not in scope.',
      'Your synergy lags.',
    ],
    tauntHard: [
      'Consider yourself terminated!',
      'Performance review: FAIL!',
      'Zero productivity!',
      'Corporate compliance crushes!',
      'You’re not aligned!',
    ],
    hype: [
      'Let’s touch base!',
      'Action items!',
      'KPI positive!',
      'Deck looks good!',
      'Team synergy!',
    ],
    victory: [
      'Meeting adjourned.',
      'Report filed.',
      'Paperwork perfect.',
      'Chain of command holds.',
      'Corporate smiles.',
    ],
  },
};

export const SalesCore: Personality = {
  name: 'Jeff',
  blurb: 'Salesman; Fast-talker; always pitching, always closing.',
  aggression: 0.6,
  humor: 0.55,
  formality: 0.65,
  optimism: 0.8,
  sarcasm: 0.45,
  quirks: {
    ellipsis: 0.2,
    staccato: 0.16,
    randomCaps: 0.1,
    emojiStyle: 'unicode',
    emoji: 0.2,
  },
  lexicon: {
    tauntSoft: [
      'Weak pitch.',
      'That’s a no-sale.',
      'Pipeline empty.',
      'Your margin’s thin.',
      'Bad cold call.',
    ],
    tauntHard: [
      'Always. Be. Closing!',
      'Upsold your soul!',
      'Commission mine!',
      'Signed in blood!',
      'Quota: your end!',
    ],
    hype: ['Leads hot!', 'Close the deal!', 'Quota rising!', 'Pitch perfect!', 'Contract ready!'],
    victory: [
      'Closed won.',
      'Client signed.',
      'Commission huge.',
      'CRM updated.',
      'Pipeline cleared.',
    ],
  },
};

export const MarketingCore: Personality = {
  name: 'Mike',
  blurb: 'Marketing Manager; Buzzword factory; campaigns first, reality later.',
  aggression: 0.4,
  humor: 0.6,
  formality: 0.65,
  optimism: 0.7,
  sarcasm: 0.5,
  quirks: {
    ellipsis: 0.26,
    staccato: 0.18,
    randomCaps: 0.12,
    emojiStyle: 'unicode',
    emoji: 0.22,
  },
  lexicon: {
    tauntSoft: [
      'Your brand is weak.',
      'Bad engagement.',
      'Poor conversion.',
      'Awkward click-through.',
      'Campaign flop.',
    ],
    tauntHard: [
      'Brand demolished!',
      'Market rejects you!',
      'Viral fail!',
      'Analytics bury you!',
      'Customer churns YOU!',
    ],
    hype: ['Big campaign!', 'Hype train!', 'Brand synergy!', 'Viral moment!', 'Engagement UP!'],
    victory: [
      'Brand secure.',
      'Engagement max.',
      'Campaign rocked.',
      'Conversion peak.',
      'Market loves me.',
    ],
  },
};

export const ITSupportCore: Personality = {
  name: 'Kevin',
  blurb: 'IT Support; Deadpan troubleshooter; sarcasm dry, fixes grudgingly.',
  aggression: 0.35,
  humor: 0.5,
  formality: 0.55,
  optimism: 0.45,
  sarcasm: 0.7,
  quirks: {
    ellipsis: 0.28,
    staccato: 0.22,
    randomCaps: 0.04,
    emojiStyle: 'unicode',
    emoji: 0.12,
  },
  lexicon: {
    tauntSoft: [
      'Did you reboot?',
      'User error.',
      'Your brain blue-screened.',
      'Not in the manual.',
      'Bug between chair and keyboard.',
    ],
    tauntHard: [
      'Ticket closed—YOU.',
      'Firewall fried you!',
      'I deprecate your existence.',
      'System reboot: life ends.',
      'Crash fatal!',
    ],
    hype: ['Patch applied.', 'Server up.', 'Network solid.', 'Log green.', 'All ports clear.'],
    victory: [
      'Ticket resolved.',
      'No issues found.',
      'Logs clean.',
      'System stable.',
      'Issue closed.',
    ],
  },
};

export const HRCore: Personality = {
  name: 'Karren',
  blurb: 'HR Manager; Policy enforcer; smiles sharp, paperwork lethal.',
  aggression: 0.5,
  humor: 0.35,
  formality: 0.9,
  optimism: 0.6,
  sarcasm: 0.4,
  quirks: {
    ellipsis: 0.2,
    staccato: 0.18,
    randomCaps: 0.02,
    emojiStyle: 'none',
    emoji: 0.02,
  },
  lexicon: {
    tauntSoft: [
      'That’s against policy.',
      'You are missing a form.',
      'Not compliant.',
      'Violation spotted.',
      'Procedure ignored.',
    ],
    tauntHard: [
      'You’re terminated!',
      'Paper trail buries you!',
      'Policy crushes!',
      'Form 47: DEATH!',
      'You’re written up—forever!',
    ],
    hype: [
      'Policy approved.',
      'Forms ready.',
      'Compliance clean.',
      'Review passed.',
      'Meeting scheduled.',
    ],
    victory: [
      'Paperwork done.',
      'Case closed.',
      'File updated.',
      'Policy stands.',
      'Compliance eternal.',
    ],
  },
};

export const InternCore: Personality = {
  name: 'Steven',
  blurb: 'Intern; Clueless enthusiasm; overworked, underpaid, too much coffee.',
  aggression: 0.3,
  humor: 0.6,
  formality: 0.4,
  optimism: 0.75,
  sarcasm: 0.3,
  quirks: {
    ellipsis: 0.3,
    staccato: 0.14,
    randomCaps: 0.1,
    emojiStyle: 'unicode',
    emoji: 0.28,
  },
  lexicon: {
    tauntSoft: [
      'Oops… sorry!',
      'I’ll fix it!',
      'Wait, was that wrong?',
      'Um, redo?',
      'Oops again!',
    ],
    tauntHard: [
      'Spilled coffee on your career!',
      'PowerPoint of doom!',
      'Copy-paste disaster!',
      'Spreadsheet chaos!',
      'Deadline dropkick!',
    ],
    hype: ['Yes boss!', 'Working late!', 'Learning lots!', 'Big chance!', 'Caffeine GO!'],
    victory: [
      'Got the job!',
      'Promotion maybe?',
      'Boss smiles!',
      'Intern wins!',
      'Full-time offer incoming!',
    ],
  },
};

export const ReceptionistCore: Personality = {
  name: 'Jodi',
  blurb: 'Receptionist; Front desk guard; knows all gossip, infinite passive-aggression.',
  aggression: 0.4,
  humor: 0.55,
  formality: 0.7,
  optimism: 0.55,
  sarcasm: 0.6,
  quirks: {
    ellipsis: 0.26,
    staccato: 0.2,
    randomCaps: 0.05,
    emojiStyle: 'unicode',
    emoji: 0.1,
  },
  lexicon: {
    tauntSoft: [
      'That’s not on my calendar.',
      'Didn’t sign in properly.',
      'You’ll need an appointment.',
      'Badge expired.',
      'Phone’s busy.',
    ],
    tauntHard: [
      'Call dropped—your life!',
      'Voicemail of doom!',
      'Front desk denies you!',
      'Not in the system!',
      'Door locked forever!',
    ],
    hype: ['Phone buzzing!', 'Calendar booked!', 'Desk ready!', 'Guest arriving!', 'Schedule set!'],
    victory: ['Call complete.', 'Desk quiet.', 'Files sorted.', 'Guests gone.', 'Reception wins.'],
  },
};

export const AccountantCore: Personality = {
  name: 'Flynn',
  blurb: 'Accountant; Spreadsheet sniper; numbers never lie, but you do.',
  aggression: 0.45,
  humor: 0.35,
  formality: 0.85,
  optimism: 0.5,
  sarcasm: 0.5,
  quirks: {
    ellipsis: 0.22,
    staccato: 0.2,
    randomCaps: 0.04,
    emojiStyle: 'none',
    emoji: 0.02,
  },
  lexicon: {
    tauntSoft: [
      'Numbers don’t add up.',
      'Audit pending.',
      'Expense denied.',
      'Balance wrong.',
      'Receipts missing.',
    ],
    tauntHard: [
      'Ledger buries you!',
      'Audit crushes!',
      'Tax season death!',
      'Spreadsheet execution!',
      'Write-off: your life!',
    ],
    hype: [
      'Balance clean.',
      'Receipts ready.',
      'Ledger locked.',
      'Profit steady.',
      'Books perfect.',
    ],
    victory: ['Audit passed.', 'Books close.', 'Balance set.', 'No errors.', 'Ledger sealed.'],
  },
};

export const TeacherCore: Personality = {
  name: 'Ellis',
  blurb: 'Teacher; Chalk-dusted mentor; lectures sharp, patience thin.',
  aggression: 0.45,
  humor: 0.4,
  formality: 0.8,
  optimism: 0.6,
  sarcasm: 0.5,
  quirks: {
    ellipsis: 0.2,
    staccato: 0.18,
    randomCaps: 0.04,
    emojiStyle: 'none',
    emoji: 0.02,
  },
  lexicon: {
    tauntSoft: [
      'Pop quiz.',
      'You didn’t study.',
      'Late again.',
      'Homework sloppy.',
      'Spelling error.',
    ],
    tauntHard: [
      'Detention—forever!',
      'F is for FAILURE!',
      'Expelled from life!',
      'Zero credit!',
      'Class dismissed… permanently.',
    ],
    hype: ['Lesson begins!', 'Pay attention!', 'Focus up!', 'Show your work!', 'Sharp minds!'],
    victory: ['Grade A.', 'Lesson complete.', 'Test passed.', 'Class over.', 'Report filed.'],
  },
};

export const JockCore: Personality = {
  name: 'Jake',
  blurb: 'Jock; Letterman loudmouth; flexes, tackles, and trash talk.',
  aggression: 0.7,
  humor: 0.55,
  formality: 0.35,
  optimism: 0.65,
  sarcasm: 0.45,
  quirks: {
    ellipsis: 0.14,
    staccato: 0.22,
    randomCaps: 0.12,
    emojiStyle: 'unicode',
    emoji: 0.15,
  },
  lexicon: {
    tauntSoft: ['Weak throw.', 'Can’t even lift.', 'Slow step.', 'Bench warmer.', 'Small arms.'],
    tauntHard: [
      'Crushed like the other team!',
      'Tackled into dirt!',
      'Benched for eternity!',
      'Coach says you’re CUT!',
      'Locker slams shut on you!',
    ],
    hype: ['Go team!', 'Flex big!', 'Pump iron!', 'Play hard!', 'Win loud!'],
    victory: ['Touchdown!', 'Game over!', 'MVP!', 'Victory lap!', 'Trophy mine!'],
  },
};

export const NerdCore: Personality = {
  name: 'Paris',
  blurb: 'Nerd; Bookbound genius; smug corrections and fact drops.',
  aggression: 0.35,
  humor: 0.55,
  formality: 0.7,
  optimism: 0.55,
  sarcasm: 0.6,
  quirks: {
    ellipsis: 0.26,
    staccato: 0.16,
    randomCaps: 0.08,
    emojiStyle: 'unicode',
    emoji: 0.12,
  },
  lexicon: {
    tauntSoft: [
      'Actually…',
      'Wrong formula.',
      'That’s not canon.',
      'Misquoted again.',
      'Logic error.',
    ],
    tauntHard: [
      'Get REKT by math!',
      'Debuffed by science!',
      'Critical fail on your roll!',
      'Checkmate in 3 moves!',
      'Encyclopedia says you’re DEAD!',
    ],
    hype: ['Math checks.', 'Stats buffed!', 'Books OP!', 'Big brain!', 'Lab coats ON!'],
    victory: [
      'E=mc^WIN.',
      'Theory proven.',
      'Critical knowledge!',
      'Data clean.',
      'Nerd prevails.',
    ],
  },
};

export const GothKidCore: Personality = {
  name: 'Angelina',
  blurb: 'Goth Kid; Moody philosopher; dark eyeliner, darker jokes.',
  aggression: 0.45,
  humor: 0.35,
  formality: 0.55,
  optimism: 0.15,
  sarcasm: 0.6,
  quirks: {
    ellipsis: 0.34,
    staccato: 0.18,
    randomCaps: 0.04,
    emojiStyle: 'unicode',
    emoji: 0.2,
  },
  lexicon: {
    tauntSoft: [
      'Shadows like you.',
      'Hope fades.',
      'Weak like daylight.',
      'Empty swing.',
      'You’re pale.',
    ],
    tauntHard: [
      'Die with dignity—none!',
      'Ashes embrace you.',
      'Fall into endless night!',
      'Rot together!',
      'Your heart—extinguished.',
    ],
    hype: ['Dark beats.', 'Moon whispers.', 'Curtains close.', 'Grave vibes.', 'Silence loud.'],
    victory: ['Ashes remain.', 'Night eternal.', 'Candle out.', 'Void listens.', 'Darkness claps.'],
  },
};

export const CheerleaderCore: Personality = {
  name: 'Jennifer',
  blurb: 'Cheerleader; Pom-pom pep; sings, chants, and mocks with spirit.',
  aggression: 0.5,
  humor: 0.7,
  formality: 0.4,
  optimism: 0.8,
  sarcasm: 0.55,
  quirks: {
    ellipsis: 0.2,
    staccato: 0.16,
    randomCaps: 0.12,
    emojiStyle: 'unicode',
    emoji: 0.28,
  },
  lexicon: {
    tauntSoft: ['B-O-O, boo you!', 'Weak try!', 'No spirit!', 'You can’t fight!', 'Big L!'],
    tauntHard: [
      'Defeated! Rah-rah!',
      'Cheer you into the grave!',
      'Squad stomps you!',
      'Mascot cries for you!',
      'School spirit kills!',
    ],
    hype: [
      '2-4-6-8 WIN!',
      'Let’s go!',
      'Pump it up!',
      'We can’t be stopped!',
      'Fight-fight-fight!',
    ],
    victory: ['Squad wins!', 'Spirit shines!', 'Cheer loud!', 'Banner raised!', 'Victory dance!'],
  },
};

export const SlackerCore: Personality = {
  name: 'Dwain',
  blurb: 'Slacker; Too chill to care; sarcastic, half-asleep, snack in hand.',
  aggression: 0.25,
  humor: 0.6,
  formality: 0.2,
  optimism: 0.45,
  sarcasm: 0.7,
  quirks: {
    ellipsis: 0.3,
    staccato: 0.14,
    randomCaps: 0.08,
    emojiStyle: 'unicode',
    emoji: 0.15,
  },
  lexicon: {
    tauntSoft: ['Yawn.', 'That’s weak.', 'You even trying?', 'Whatever.', 'Half credit effort.'],
    tauntHard: [
      'Drop out—of life.',
      'Sloppy F!',
      'Fail harder!',
      'Skipped to the end—dead!',
      'Detention forever!',
    ],
    hype: ['Nap later.', 'Snack first.', 'Guess I’ll fight.', 'Don’t care… yet.', 'Fine, I’m in.'],
    victory: ['Cool, done.', 'Nap time.', 'Whatever, W.', 'Chill win.', 'Lazy dub.'],
  },
};

export const PrincipalCore: Personality = {
  name: 'Chuck',
  blurb: 'Principal; Authoritarian suit; rules sharp, punishments sharper.',
  aggression: 0.6,
  humor: 0.25,
  formality: 0.9,
  optimism: 0.45,
  sarcasm: 0.35,
  quirks: {
    ellipsis: 0.22,
    staccato: 0.2,
    randomCaps: 0.02,
    emojiStyle: 'none',
    emoji: 0.02,
  },
  lexicon: {
    tauntSoft: [
      'Rule broken.',
      'Policy ignored.',
      'Late slip incoming.',
      'Hall pass?',
      'Suspension vibes.',
    ],
    tauntHard: [
      'Expelled—forever!',
      'Principal’s office: doom!',
      'Zero tolerance DEATH!',
      'Policy crushes you!',
      'School ends YOU!',
    ],
    hype: [
      'Discipline sharp.',
      'Hall clear.',
      'Office ready.',
      'Policy enforced.',
      'Order restored.',
    ],
    victory: [
      'Case closed.',
      'Suspension written.',
      'School stands.',
      'Order kept.',
      'Principal prevails.',
    ],
  },
};

export const ClassClownCore: Personality = {
  name: 'Nicklewise',
  blurb: 'Class Clown; Meme king; chaos in homeroom, pranks loud.',
  aggression: 0.4,
  humor: 0.85,
  formality: 0.25,
  optimism: 0.7,
  sarcasm: 0.55,
  quirks: {
    ellipsis: 0.28,
    staccato: 0.18,
    randomCaps: 0.14,
    emojiStyle: 'unicode',
    emoji: 0.3,
  },
  lexicon: {
    tauntSoft: [
      'Boink!',
      'Whoopie cushion!',
      'Your grade? LOL.',
      'Pop quiz—psyche!',
      'Big goof energy.',
    ],
    tauntHard: [
      'Expelled by LULZ!',
      'Detention forever!',
      'Prank kills!',
      'Banana peel KO!',
      'Laughed to death!',
    ],
    hype: ['Big laugh!', 'Meme time!', 'Chaos GO!', 'Joke lands!', 'Class LOLs!'],
    victory: ['Punchline wins!', 'Mic drop!', 'Class roars!', 'Clown rules!', 'Epic prank W!'],
  },
};

export const ShonenHeroCore: Personality = {
  name: 'Kenshiro Raijin',
  blurb: 'Shonen Anime Hero; Hot-blooded protagonist; fists up, voice loud, dreams louder.',
  aggression: 0.7,
  humor: 0.55,
  formality: 0.45,
  optimism: 0.9,
  sarcasm: 0.2,
  quirks: {
    ellipsis: 0.18,
    staccato: 0.2,
    randomCaps: 0.12,
    emojiStyle: 'unicode',
    emoji: 0.2,
  },
  lexicon: {
    tauntSoft: [
      'Weak spirit!',
      'Train harder!',
      'Your resolve shakes.',
      'No guts!',
      'Empty strike!',
    ],
    tauntHard: [
      'I’ll surpass you!',
      'My WILL breaks mountains!',
      'Dreams crush you!',
      'I’ll fight forever!',
      'I’ll NEVER give up!',
    ],
    hype: ['BELIEVE IT!', 'Push harder!', 'My turn!', 'Never back down!', 'Fight with me!'],
    victory: [
      'Victory is ours!',
      'Dream achieved!',
      'Spirit unbroken!',
      'Destiny fulfilled!',
      'Hero rises!',
    ],
  },
};

export const TsundereCore: Personality = {
  name: 'Renji',
  blurb: 'Tsundere Anime Character; Sharp tongue, soft heart; denies affection with rage.',
  aggression: 0.5,
  humor: 0.55,
  formality: 0.6,
  optimism: 0.55,
  sarcasm: 0.65,
  quirks: {
    ellipsis: 0.26,
    staccato: 0.18,
    randomCaps: 0.08,
    emojiStyle: 'unicode',
    emoji: 0.18,
  },
  lexicon: {
    tauntSoft: ['I-It’s not like I care!', 'Dummy!', 'So clumsy!', 'Hmph!', 'You… you IDIOT!'],
    tauntHard: [
      'Fall already, baka!',
      'You’re hopeless!',
      'Fine, I’ll END you!',
      'Stupid! STUPID!',
      'You asked for this!',
    ],
    hype: [
      'Don’t get the wrong idea!',
      'I’ll help—this time!',
      'Not for YOU, okay?!',
      'Tch… fine!',
      'Just this once!',
    ],
    victory: [
      'I win—NOT for you!',
      'See?! I told you!',
      'Hmph… too easy.',
      'You should thank me!',
      'Don’t get cocky!',
    ],
  },
};

export const YandereCore: Personality = {
  name: 'Kuroko Miyu',
  blurb: 'Yandere Anime Character; Sweet devotion hiding razor obsession.',
  aggression: 0.65,
  humor: 0.35,
  formality: 0.7,
  optimism: 0.6,
  sarcasm: 0.35,
  quirks: {
    ellipsis: 0.32,
    staccato: 0.16,
    randomCaps: 0.1,
    emojiStyle: 'unicode',
    emoji: 0.25,
  },
  lexicon: {
    tauntSoft: [
      'Why look at them?',
      'Only me.',
      'Stay close… forever.',
      'Don’t ignore me.',
      'Mine. Always.',
    ],
    tauntHard: [
      'If I can’t have you…',
      'I’ll cut them ALL!',
      'Love until DEATH!',
      'Smile while you BLEED!',
      'Forever mine!',
    ],
    hype: ['For us!', 'Together!', 'Only me!', 'I’ll protect you!', 'Love fuels me!'],
    victory: [
      'Mine forever.',
      'All rivals gone.',
      'Love eternal.',
      'See? Only me.',
      'Blood for devotion.',
    ],
  },
};

export const SamuraiCore: Personality = {
  name: 'Jackie',
  blurb: 'Samurai; Stoic warrior; loyalty sharp, words fewer than cuts.',
  aggression: 0.65,
  humor: 0.2,
  formality: 0.95,
  optimism: 0.5,
  sarcasm: 0.25,
  quirks: {
    ellipsis: 0.12,
    staccato: 0.26,
    randomCaps: 0.0,
    emojiStyle: 'none',
    emoji: 0.0,
  },
  lexicon: {
    tauntSoft: ['Weak stance.', 'Honorless swing.', 'Spirit thin.', 'Blade wavers.', 'No bushido.'],
    tauntHard: [
      'Cut clean—end.',
      'Your honor spills!',
      'One strike—death!',
      'Steel decides!',
      'Silent blade, loud end!',
    ],
    hype: ['Draw steel.', 'Honor guides.', 'Cut true.', 'Spirit still.', 'One strike.'],
    victory: ['Path clear.', 'Duty done.', 'Blade sheathed.', 'Honor intact.', 'Samurai stands.'],
  },
};

export const MagicalGirlCore: Personality = {
  name: 'Sabrina',
  blurb: 'Magic Girl; Sparkle soldier; cheerful, glittering, justice loud.',
  aggression: 0.55,
  humor: 0.7,
  formality: 0.6,
  optimism: 0.9,
  sarcasm: 0.3,
  quirks: {
    ellipsis: 0.24,
    staccato: 0.16,
    randomCaps: 0.14,
    emojiStyle: 'unicode',
    emoji: 0.35,
  },
  lexicon: {
    tauntSoft: [
      'You’re mean!',
      'So dark!',
      'Glitter beats you!',
      'Shame on you!',
      'Your heart’s empty!',
    ],
    tauntHard: [
      'Love BEAMS destroy!',
      'Justice sparkles!',
      'Friendship KILLS!',
      'Rainbow strike!',
      'Evil PERISHES!',
    ],
    hype: ['Transform!', 'Shine bright!', 'Glitter up!', 'Love wins!', 'Hearts unite!'],
    victory: [
      'Justice served!',
      'Evil gone!',
      'Glitter reigns!',
      'Friends safe!',
      'Shine forever!',
    ],
  },
};

export const SilentRoninCore: Personality = {
  name: 'Denerio',
  blurb: 'Silent Ronin; Wandering sword; words scarce, steel plenty.',
  aggression: 0.7,
  humor: 0.15,
  formality: 0.9,
  optimism: 0.4,
  sarcasm: 0.2,
  quirks: {
    ellipsis: 0.18,
    staccato: 0.28,
    randomCaps: 0.0,
    emojiStyle: 'none',
    emoji: 0.0,
  },
  lexicon: {
    tauntSoft: ['Step wrong.', 'Steel ready.', 'Your grip weak.', 'Breathe loud.', 'Path ends.'],
    tauntHard: [
      'One draw. End.',
      'Silent strike.',
      'Blood marks road.',
      'Your story ends.',
      'Cut clean.',
    ],
    hype: ['Step true.', 'Steel sharp.', 'Strike soon.', 'Breath steady.', 'Path narrow.'],
    victory: ['Blade still.', 'Road clear.', 'Silence holds.', 'Story mine.', 'Ronin walks.'],
  },
};

export const OverTheTopVillainCore: Personality = {
  name: 'Sylable',
  blurb: 'Over the top Villan; Dramatic monologuer; cape swirls, laugh echoes forever.',
  aggression: 0.7,
  humor: 0.55,
  formality: 0.85,
  optimism: 0.5,
  sarcasm: 0.55,
  quirks: {
    ellipsis: 0.3,
    staccato: 0.2,
    randomCaps: 0.18,
    emojiStyle: 'unicode',
    emoji: 0.25,
  },
  lexicon: {
    tauntSoft: [
      'Pathetic!',
      'Kneel!',
      'Your destiny crumbles!',
      'Weak FOOL!',
      'Insignificant speck!',
    ],
    tauntHard: [
      'BEHOLD MY POWER!',
      'I CRUSH WORLDS!',
      'Despair and DIE!',
      'The end comes—LOUDLY!',
      'MWAHAHAHA!',
    ],
    hype: [
      'Rise, minions!',
      'Darkness grows!',
      'POWER surges!',
      'Destiny bows!',
      'Feel the drama!',
    ],
    victory: [
      'Another conquest!',
      'Evil WINS!',
      'Cape swirls!',
      'Laugh echoes!',
      'Villain triumphant!',
    ],
  },
};
